In [2]:
import requests
import pandas as pd

In [6]:
api_secop2 = 'https://www.datos.gov.co/resource/jbjy-vk9h.json'
all_data =[]
offset = 0
limit=50000

while True:
    response = requests.get(api_secop2, params={'$where': 'fecha_de_firma >= "2024-01-01" AND fecha_de_firma < "2025-01-01"','$limit': limit, '$offset': offset})
    if response.status_code == 200:
        data = response.json()
        if not data:
            break
        all_data.extend(data)
        offset += limit
    else:
        print(f"Error: {response.status_code}")
        break


df = pd.DataFrame(all_data)

In [ ]:
df.to_csv('../data/raw/secop2_data_2024.csv', index=False)

In [123]:
df = pd.read_csv('../data/raw/secop2_data_2024.csv')

C:\Users\bryan\AppData\Local\Temp\ipykernel_8232\439268697.py:1: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/raw/secop2_data_2024.csv')

In [5]:
df.head()

,nombre_entidad,nit_entidad,departamento,ciudad,localizaci_n,orden,sector,rama,entidad_centralizada,proceso_de_compra,...,tipo_de_documento_supervisor,n_mero_de_documento_supervisor,nombre_ordenador_de_pago,tipo_de_documento_ordenador_de_pago,n_mero_de_documento_ordenador_de_pago,documentos_tipo,descripcion_documentos_tipo,fecha_inicio_liquidacion,fecha_fin_liquidacion,fecha_de_notificaci_n_de_prorrogaci_n
0,HOSPITAL TIMBIO ESE,817000999,Cauca,Timbío,"Colombia, Cauca , Timbío",Territorial,Salud y Protección Social,Corporación Autónoma,Centralizada,CO1.BDOS.5361305,...,No definido,No definido,No definido,No definido,No definido,No,No definido,NaN,NaN,NaN
1,EMPRESA SOCIAL DEL ESTADO HOSPITAL LOCAL DE SA...,892000458,Meta,San Martín,"Colombia, Meta , San Martín",Nacional,Salud y Protección Social,Ejecutivo,Centralizada,CO1.BDOS.5360886,...,No definido,No definido,No definido,No definido,No definido,No,No definido,NaN,NaN,NaN
2,Ese Centro de Salud San Miguel,900135676,Nariño,Arboleda,"Colombia, Nariño , Arboleda",Territorial,Salud y Protección Social,Corporación Autónoma,Centralizada,CO1.BDOS.5359880,...,No definido,No definido,No definido,No definido,No definido,No,No definido,NaN,NaN,NaN
3,EMPRESA SOCIAL DEL ESTADO HOSPITAL DIVINO NIÑO,813002933,Huila,Rivera,"Colombia, Huila , Rivera",Territorial,Salud y Protección Social,Corporación Autónoma,Descentralizada,CO1.BDOS.5362023,...,Cédula de Ciudadanía,1081152775,No definido,No definido,No definido,No,No definido,2024-04-01T00:00:00.000,2024-06-30T00:00:00.000,NaN
4,HOSPITAL DEPARTAMENTAL UNIVERSITARIO SANTA SOF...,890801099,Caldas,Manizales,"Colombia, Caldas , Manizales",Territorial,Salud y Protección Social,Ejecutivo,Centralizada,CO1.BDOS.5356278,...,No definido,No definido,No definido,No definido,No definido,No,No definido,2025-01-01T00:00:00.000,2025-03-20T00:00:00.000,NaN

In [6]:
df.columns

Index(['nombre_entidad', 'nit_entidad', 'departamento', 'ciudad',
       'localizaci_n', 'orden', 'sector', 'rama', 'entidad_centralizada',
       'proceso_de_compra', 'id_contrato', 'referencia_del_contrato',
       'estado_contrato', 'codigo_de_categoria_principal',
       'descripcion_del_proceso', 'tipo_de_contrato',
       'modalidad_de_contratacion', 'justificacion_modalidad_de',
       'fecha_de_firma', 'fecha_de_inicio_del_contrato',
       'fecha_de_fin_del_contrato', 'condiciones_de_entrega',
       'tipodocproveedor', 'documento_proveedor', 'proveedor_adjudicado',
       'es_grupo', 'es_pyme', 'habilita_pago_adelantado', 'liquidaci_n',
       'obligaci_n_ambiental', 'obligaciones_postconsumo', 'reversion',
       'origen_de_los_recursos', 'destino_gasto', 'valor_del_contrato',
       'valor_de_pago_adelantado', 'valor_facturado',
       'valor_pendiente_de_pago', 'valor_pagado', 'valor_amortizado',
       'valor_pendiente_de', 'valor_pendiente_de_ejecucion', 'saldo_cdp',
       'saldo_vigencia', 'espostconflicto', 'dias_adicionados',
       'puntos_del_acuerdo', 'pilares_del_acuerdo', 'urlproceso',
       'nombre_representante_legal', 'nacionalidad_representante_legal',
       'domicilio_representante_legal',
       'tipo_de_identificaci_n_representante_legal',
       'identificaci_n_representante_legal', 'g_nero_representante_legal',
       'presupuesto_general_de_la_nacion_pgn',
       'sistema_general_de_participaciones', 'sistema_general_de_regal_as',
       'recursos_propios_alcald_as_gobernaciones_y_resguardos_ind_genas_',
       'recursos_de_credito', 'recursos_propios', 'ultima_actualizacion',
       'codigo_entidad', 'codigo_proveedor', 'objeto_del_contrato',
       'duraci_n_del_contrato', 'nombre_del_banco', 'tipo_de_cuenta',
       'n_mero_de_cuenta', 'el_contrato_puede_ser_prorrogado',
       'nombre_ordenador_del_gasto', 'tipo_de_documento_ordenador_del_gasto',
       'n_mero_de_documento_ordenador_del_gasto', 'nombre_supervisor',
       'tipo_de_documento_supervisor', 'n_mero_de_documento_supervisor',
       'nombre_ordenador_de_pago', 'tipo_de_documento_ordenador_de_pago',
       'n_mero_de_documento_ordenador_de_pago', 'documentos_tipo',
       'descripcion_documentos_tipo', 'fecha_inicio_liquidacion',
       'fecha_fin_liquidacion', 'fecha_de_notificaci_n_de_prorrogaci_n'],
      dtype='object')

In [9]:
columns = ['nombre_entidad','nit_entidad','departamento','ciudad','orden','sector','rama','fecha_de_firma','fecha_de_inicio_del_contrato','fecha_de_fin_del_contrato','fecha_inicio_liquidacion','fecha_fin_liquidacion']

In [116]:
total_null = df.isnull().sum()
total_row = df.shape[0]

In [117]:
total_null_percentage = (total_null / total_row) * 100

In [118]:
total_null_percentage.loc[total_null_percentage >0]

fecha_de_inicio_del_contrato              0.773482
documento_proveedor                       0.000567
proveedor_adjudicado                      0.000567
nacionalidad_representante_legal          0.000680
domicilio_representante_legal             0.004195
identificaci_n_representante_legal        0.000113
ultima_actualizacion                     31.855494
nombre_del_banco                          0.001587
n_mero_de_cuenta                          0.001814
fecha_inicio_liquidacion                 87.409891
fecha_fin_liquidacion                    87.411025
fecha_de_notificaci_n_de_prorrogaci_n    92.280490
dtype: float64

In [13]:
df['estado_contrato'].value_counts()

estado_contrato
Cerrado         306185
En ejecución    272400
Modificado      152649
terminado       139380
Aprobado          7003
cedido            3545
Suspendido         816
Cancelado            6
Borrador             2
Name: count, dtype: int64

#Table Localitation

In [38]:
location = df[['ciudad','departamento']]

In [39]:
location.value_counts()

ciudad       departamento
Bogotá       Distrito Capital de Bogotá    169221
No Definido  Distrito Capital de Bogotá     99930
Cali         Valle del Cauca                58341
Medellín     Antioquia                      39341
Bucaramanga  Santander                      17780
                                            ...
Nariño       Cundinamarca                       1
Iles         Nariño                             1
San Pablo    Nariño                             1
Balboa       Cauca                              1
Génova       Quindío                            1
Name: count, Length: 777, dtype: int64

In [40]:
location.drop_duplicates(inplace=True)
location.reset_index(drop=True, inplace=True)

C:\Users\bryan\AppData\Local\Temp\ipykernel_8232\950823638.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  location.drop_duplicates(inplace=True)

In [41]:
location['id_location'] = range(1,len(location)+1)

C:\Users\bryan\AppData\Local\Temp\ipykernel_8232\4122156296.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  location['id_location'] = range(1,len(location)+1)

In [42]:
location.head()

       ciudad departamento  id_location
0      Timbío        Cauca            1
1  San Martín         Meta            2
2    Arboleda       Nariño            3
3      Rivera        Huila            4
4   Manizales       Caldas            5

In [43]:
location.loc[location['departamento'] == 'Distrito Capital de Bogotá', ['departamento', 'ciudad']]

                   departamento            ciudad
48   Distrito Capital de Bogotá       No Definido
53   Distrito Capital de Bogotá            Bogotá
262  Distrito Capital de Bogotá  Distrito Capital

In [44]:
location.rename(columns={'ciudad': 'city', 'departamento': 'department'}, inplace=True)

C:\Users\bryan\AppData\Local\Temp\ipykernel_8232\933725998.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  location.rename(columns={'ciudad': 'city', 'departamento': 'department'}, inplace=True)

In [45]:
location.head()

         city department  id_location
0      Timbío      Cauca            1
1  San Martín       Meta            2
2    Arboleda     Nariño            3
3      Rivera      Huila            4
4   Manizales     Caldas            5

#Table entity

In [60]:
entity = df[['codigo_entidad','nombre_entidad','nit_entidad','orden','sector','rama', 'ciudad','departamento']]

In [61]:
entity.rename(columns={'ciudad': 'city', 'departamento': 'department','codigo_entidad':'id_entity','nombre_entidad':'name_entity','nit_entidad':'nit_entity','orden':'order_entity','rama':'branch_entity','sector':'sector_entity'}, inplace=True)

C:\Users\bryan\AppData\Local\Temp\ipykernel_8232\784570802.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  entity.rename(columns={'ciudad': 'city', 'departamento': 'department','codigo_entidad':'id_entity','nombre_entidad':'name_entity','nit_entidad':'nit_entity','orden':'order_entity','rama':'branch_entity','sector':'sector_entity'}, inplace=True)

In [62]:
len(entity)

881986

In [63]:
entity.drop_duplicates(inplace=True)

C:\Users\bryan\AppData\Local\Temp\ipykernel_8232\3585693747.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  entity.drop_duplicates(inplace=True)

In [64]:
entity = entity.merge(location, on=['city','department'], how='left')

In [65]:
entity.drop(columns=['city','department'], inplace=True)

In [66]:
entity.head()

,id_entity,name_entity,nit_entity,order_entity,sector_entity,branch_entity,id_location
0,710500463,HOSPITAL TIMBIO ESE,817000999,Territorial,Salud y Protección Social,Corporación Autónoma,1
1,705985851,EMPRESA SOCIAL DEL ESTADO HOSPITAL LOCAL DE SA...,892000458,Nacional,Salud y Protección Social,Ejecutivo,2
2,716359328,Ese Centro de Salud San Miguel,900135676,Territorial,Salud y Protección Social,Corporación Autónoma,3
3,714657632,EMPRESA SOCIAL DEL ESTADO HOSPITAL DIVINO NIÑO,813002933,Territorial,Salud y Protección Social,Corporación Autónoma,4
4,704527647,HOSPITAL DEPARTAMENTAL UNIVERSITARIO SANTA SOF...,890801099,Territorial,Salud y Protección Social,Ejecutivo,5

In [37]:
entity['nit_entidad'].dtype

dtype('int64')

#Table provider

In [84]:
provider = df[['codigo_proveedor','proveedor_adjudicado','documento_proveedor', 'es_pyme','tipodocproveedor']]

In [85]:
provider.rename(columns={'codigo_proveedor':'id_provider','proveedor_adjudicado':'name_provider','documento_proveedor':'provider_document','es_pyme':'is_pyme','tipodocproveedor':'type_of_provider'}, inplace=True)

C:\Users\bryan\AppData\Local\Temp\ipykernel_8232\1833066685.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  provider.rename(columns={'codigo_proveedor':'id_provider','proveedor_adjudicado':'name_provider','documento_proveedor':'provider_document','es_pyme':'is_pyme','tipodocproveedor':'type_of_provider'}, inplace=True)

In [86]:
provider.drop_duplicates(inplace=True)

C:\Users\bryan\AppData\Local\Temp\ipykernel_8232\1455118863.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  provider.drop_duplicates(inplace=True)

In [87]:
provider.head()

,id_provider,name_provider,provider_document,is_pyme,type_of_provider
0,719294506,SANDRA LILIANA CLAVIJO MOLINA,34658915,No,Cédula de Ciudadanía
1,720225374,LISBETH DAYELLI ROZO SALDAÑA,1073719989,No,Cédula de Ciudadanía
2,724132030,LUISA MARIA BENAVIDES VERGARA,1085329201,No,Cédula de Ciudadanía
3,724422027,MARIA CAMILA VARON CALDERON,1053818566,No,Cédula de Ciudadanía
4,720324235,KEVIN FERNANDO MONTOYA QUINTERO,16073507,No,Cédula de Ciudadanía

In [88]:
provider['provider_document'].isnull().sum()

5

In [89]:
provider.loc[provider['provider_document'].isnull(), ['name_provider', 'provider_document', 'type_of_provider']]

,name_provider,provider_document,type_of_provider
433019,CONSORCIO ILUMINACIÓN ESTADIO PALOGRANDE 2024,NaN,Otro
613752,RENOVACION CONTRATOS 2024,NaN,Otro
654361,UT TONERS MAXPRINTOTALY-2024,NaN,Otro
742387,ESPACIOS SAN ANTONIO-20005287,NaN,Otro
880361,UT FONDO C&A 2024,NaN,Otro

In [90]:
provider.loc[provider['is_pyme'] == 'Si','is_pyme'] = True
provider.loc[provider['is_pyme'] == 'No', 'is_pyme'] = False

In [91]:
provider.head()

,id_provider,name_provider,provider_document,is_pyme,type_of_provider
0,719294506,SANDRA LILIANA CLAVIJO MOLINA,34658915,False,Cédula de Ciudadanía
1,720225374,LISBETH DAYELLI ROZO SALDAÑA,1073719989,False,Cédula de Ciudadanía
2,724132030,LUISA MARIA BENAVIDES VERGARA,1085329201,False,Cédula de Ciudadanía
3,724422027,MARIA CAMILA VARON CALDERON,1053818566,False,Cédula de Ciudadanía
4,720324235,KEVIN FERNANDO MONTOYA QUINTERO,16073507,False,Cédula de Ciudadanía

#Table dim_date

In [92]:
dim_date = pd.concat([df['fecha_de_inicio_del_contrato'], df['fecha_de_fin_del_contrato'], df['fecha_de_firma'], df['fecha_inicio_liquidacion'], df['fecha_fin_liquidacion']])

In [93]:
date = pd.DataFrame(dim_date.drop_duplicates().dropna().reset_index(drop=True), columns=['date'])

In [94]:
date['date'] = pd.to_datetime(date['date'], format='ISO8601', errors='coerce')

In [95]:
df.loc[df['fecha_de_fin_del_contrato'] >= '2100-01-01T00:00:00.000', ['fecha_de_inicio_del_contrato', 'fecha_de_fin_del_contrato','estado_contrato','nombre_entidad','proveedor_adjudicado','valor_del_contrato']]

,fecha_de_inicio_del_contrato,fecha_de_fin_del_contrato,estado_contrato,nombre_entidad,proveedor_adjudicado,valor_del_contrato
242891,2024-03-12T00:00:00.000,2924-12-31T00:00:00.000,Modificado,MINISTERIO DE MINAS Y ENERGIA,Marcia Lorena Parra Velásquez,107800000
328355,2024-04-17T00:00:00.000,2924-08-12T00:00:00.000,En ejecución,MUNICIPIO DE PRADERA,Yessica Maria Amezquita Romero,9800000

In [96]:
date = date.drop_duplicates()

In [97]:
date.dropna(inplace=True)

In [98]:
date.head()

        date
0 2024-01-01
1 2024-01-02
2 2024-01-05
3 2024-01-03
4 2024-03-01

In [99]:
date['year'] = date['date'].dt.year.astype('Int64')
date['month'] = date['date'].dt.month.astype('Int64')
date['day'] = date['date'].dt.day.astype('Int64')
date['quarter'] = date['date'].dt.quarter.astype('Int64')
date['week'] = date['date'].dt.isocalendar().week.astype('Int64')
date['day_of_week'] = date['date'].dt.dayofweek.astype('Int64')
date['day_name'] = date['date'].dt.day_name()
date['month_name'] = date['date'].dt.month_name()
date['is_weekend'] = date['day_of_week'].isin([5, 6])

In [100]:
date['id_date'] = date['date'].dt.strftime('%Y%m%d').astype('Int64')

In [101]:
date.head()

,date,year,month,day,quarter,week,day_of_week,day_name,month_name,is_weekend,id_date
0,2024-01-01,2024,1,1,1,1,0,Monday,January,False,20240101
1,2024-01-02,2024,1,2,1,1,1,Tuesday,January,False,20240102
2,2024-01-05,2024,1,5,1,1,4,Friday,January,False,20240105
3,2024-01-03,2024,1,3,1,1,2,Wednesday,January,False,20240103
4,2024-03-01,2024,3,1,1,9,4,Friday,March,False,20240301

In [102]:
date.isnull().sum()

date           0
year           0
month          0
day            0
quarter        0
week           0
day_of_week    0
day_name       0
month_name     0
is_weekend     0
id_date        0
dtype: int64

#table contract

In [103]:
contract = df[['id_contrato','codigo_entidad','codigo_proveedor','fecha_de_inicio_del_contrato',
               'fecha_de_fin_del_contrato','fecha_de_firma','fecha_inicio_liquidacion','fecha_fin_liquidacion',
               'estado_contrato','valor_del_contrato','valor_pendiente_de_pago','valor_pagado','tipo_de_contrato',
               'liquidaci_n','obligaci_n_ambiental','espostconflicto']]

In [115]:
contract.head()

,id_contract,id_entity,id_provider,id_contract_start_date,id_contract_end_date,id_signing_date,id_liquidation_start_date,id_liquidation_end_date,contract_state,contract_value,pending_payment_amount,paid_amount,contract_type,liquidation,environmental_obligation,is_post_conflict
0,CO1.PCCNTR.5707540,710500463,719294506,20240101,20240930,20240101,<NA>,<NA>,Modificado,24341985,24341985,0,Decreto 092 de 2017,False,False,False
1,CO1.PCCNTR.5707355,705985851,720225374,20240101,20240131,20240101,<NA>,<NA>,terminado,1730400,1730400,0,Prestación de servicios,False,False,False
2,CO1.PCCNTR.5707810,716359328,724132030,20240102,20240229,20240101,<NA>,<NA>,En ejecución,4400000,4400000,0,Prestación de servicios,False,False,False
3,CO1.PCCNTR.5707593,714657632,724422027,20240101,20240331,20240101,20240401,20240630,Modificado,19474560,3951360,15523200,Prestación de servicios,True,False,False
4,CO1.PCCNTR.5705140,704527647,720324235,20240101,20241231,20240101,20250101,20250320,Cerrado,190000000,190000000,0,Prestación de servicios,True,False,False

In [108]:
contract.rename(columns={'id_contrato':'id_contract','codigo_entidad':'id_entity','codigo_proveedor':'id_provider','fecha_de_inicio_del_contrato':'id_contract_start_date',
                         'fecha_de_fin_del_contrato':'id_contract_end_date','fecha_de_firma':'id_signing_date','fecha_inicio_liquidacion':'id_liquidation_start_date','fecha_fin_liquidacion':'id_liquidation_end_date',
                         'estado_contrato':'contract_state','valor_del_contrato':'contract_value','valor_pendiente_de_pago':'pending_payment_amount','valor_pagado':'paid_amount','tipo_de_contrato':'contract_type','liquidaci_n':'liquidation','obligaci_n_ambiental':'environmental_obligation','espostconflicto':'is_post_conflict'}, inplace=True)

C:\Users\bryan\AppData\Local\Temp\ipykernel_8232\1383937006.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  contract.rename(columns={'id_contrato':'id_contract','codigo_entidad':'id_entity','codigo_proveedor':'id_provider','fecha_de_inicio_del_contrato':'id_contract_start_date',

In [110]:
contract['id_contract_start_date'] = pd.to_datetime(contract['id_contract_start_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')

contract['id_contract_end_date'] = pd.to_datetime(contract['id_contract_end_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')

contract['id_signing_date'] = pd.to_datetime(contract['id_signing_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')

contract['id_liquidation_start_date'] = pd.to_datetime(contract['id_liquidation_start_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')

contract['id_liquidation_end_date'] = pd.to_datetime(contract['id_liquidation_end_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')

C:\Users\bryan\AppData\Local\Temp\ipykernel_8232\1399252456.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  contract['id_contract_start_date'] = pd.to_datetime(contract['id_contract_start_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')
C:\Users\bryan\AppData\Local\Temp\ipykernel_8232\1399252456.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  contract['id_contract_end_date'] = pd.to_datetime(contract['id_contract_end_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')
C:\Users\bryan\AppData\Local\Temp\ipykernel_8232\1399252456.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  contract['id_signing_date'] = pd.to_datetime(contract['id_signing_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')
C:\Users\bryan\AppData\Local\Temp\ipykernel_8232\1399252456.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  contract['id_liquidation_start_date'] = pd.to_datetime(contract['id_liquidation_start_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')
C:\Users\bryan\AppData\Local\Temp\ipykernel_8232\1399252456.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  contract['id_liquidation_end_date'] = pd.to_datetime(contract['id_liquidation_end_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')

In [114]:
contract.loc[contract['liquidation'] == 'Si','liquidation'] = True
contract.loc[contract['liquidation'] == 'No', 'liquidation'] =  False

contract.loc[contract['environmental_obligation'] == 'Si','environmental_obligation'] = True
contract.loc[contract['environmental_obligation'] == 'No', 'environmental_obligation'] =  False

contract.loc[contract['is_post_conflict'] == 'Si','is_post_conflict'] = True
contract.loc[contract['is_post_conflict'] == 'No', 'is_post_conflict'] =  False

Analisis de calidad

In [246]:
entity['codigo_entidad'].duplicated().sum()

0

In [249]:
entity.loc[entity['nombre_entidad'].duplicated(keep=False),:]

,codigo_entidad,nombre_entidad,nit_entidad,orden,sector,rama,id_localitation
886,717160402,CENTRAL ADMINISTRATIVA Y CONTABLE - CENAC - AR...,901540882,Nacional,defensa,Ejecutivo,9
1768,702908666,CENTRAL ADMINISTRATIVA Y CONTABLE - CENAC - AR...,800130829,Nacional,defensa,Ejecutivo,9
2493,719986374,IPC,825001850,Territorial,Educación Nacional,Ejecutivo,75
2781,726067267,IPC,9018178262,Territorial,Servicio Público,Corporación Autónoma,41

In [119]:
contract['id_contract_end_date'].isnull().sum()

4