In [1]:
import requests
import pandas as pd
import unicodedata

In [6]:
api_secop2 = 'https://www.datos.gov.co/resource/jbjy-vk9h.json'
all_data =[]
offset = 0
limit=50000

while True:
    response = requests.get(api_secop2, params={'$where': 'fecha_de_firma >= "2024-01-01" AND fecha_de_firma < "2025-01-01"','$limit': limit, '$offset': offset})
    if response.status_code == 200:
        data = response.json()
        if not data:
            break
        all_data.extend(data)
        offset += limit
    else:
        print(f"Error: {response.status_code}")
        break


df = pd.DataFrame(all_data)

In [2]:
df = pd.read_csv('../data/raw/secop2_data_2024-2025.csv')

C:\Users\bryan\AppData\Local\Temp\ipykernel_12004\559596961.py:1: DtypeWarning: Columns (0: documento_proveedor, 1: ultima_actualizacion, 2: codigo_proveedor) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/raw/secop2_data_2024-2025.csv')

In [37]:
df.loc[df['codigo_entidad'] == 710500463, ['codigo_entidad','id_contrato', 'nombre_entidad', 'proveedor_adjudicado', 'fecha_de_firma', 'departamento','nit_entidad', 'valor_del_contrato']]

,codigo_entidad,id_contrato,nombre_entidad,proveedor_adjudicado,fecha_de_firma,departamento,nit_entidad,valor_del_contrato
0,710500463,CO1.PCCNTR.5707540,HOSPITAL TIMBIO ESE,SANDRA LILIANA CLAVIJO MOLINA,2024-01-01T00:00:00.000,Cauca,817000999,24341985
92,710500463,CO1.PCCNTR.5707601,HOSPITAL TIMBIO ESE,PROFESIONALES Y LIDERES DE LA SEGURIDAD,2024-01-01T00:00:00.000,Cauca,817000999,16235299
137,710500463,CO1.PCCNTR.5707310,HOSPITAL TIMBIO ESE,SIEMPO,2024-01-01T00:00:00.000,Cauca,817000999,80584608
151,710500463,CO1.PCCNTR.5705629,HOSPITAL TIMBIO ESE,MONICA ANDREA COLLAZOS TACUE,2024-01-01T00:00:00.000,Cauca,817000999,4400000
301,710500463,CO1.PCCNTR.5707505,HOSPITAL TIMBIO ESE,LEDY DORANI VELASCO ACOSTA,2024-01-01T00:00:00.000,Cauca,817000999,28612500
...,...,...,...,...,...,...,...,...
932549,710500463,CO1.PCCNTR.7246054,HOSPITAL TIMBIO ESE,NOLBERTO CORREDOR ROMERO,2025-01-16T00:00:00.000,Cauca,817000999,20000000
932568,710500463,CO1.PCCNTR.7255464,HOSPITAL TIMBIO ESE,DIANA YEPES MUÑOZ,2025-01-16T00:00:00.000,Cauca,817000999,9537500
1387451,710500463,CO1.PCCNTR.7889203,MUNICIPIO DE TIMBIO,HOSPITAL TIMBIO ESE,2025-05-21T00:00:00.000,Cauca,891500742,397846937
1391807,710500463,CO1.PCCNTR.7905673,MUNICIPIO DE TIMBIO,HOSPITAL TIMBIO ESE,2025-05-22T00:00:00.000,Cauca,891500742,441566290
1795301,710500463,CO1.PCCNTR.8555508,GOBERNACIÓN DEL CAUCA,HOSPITAL TIMBIO ESE,2025-11-07T00:00:00.000,Cauca,891580016,698491429

In [5]:
df.head()

,nombre_entidad,nit_entidad,departamento,ciudad,localizaci_n,orden,sector,rama,entidad_centralizada,proceso_de_compra,...,tipo_de_documento_supervisor,n_mero_de_documento_supervisor,nombre_ordenador_de_pago,tipo_de_documento_ordenador_de_pago,n_mero_de_documento_ordenador_de_pago,documentos_tipo,descripcion_documentos_tipo,fecha_inicio_liquidacion,fecha_fin_liquidacion,fecha_de_notificaci_n_de_prorrogaci_n
0,HOSPITAL TIMBIO ESE,817000999,Cauca,Timbío,"Colombia, Cauca , Timbío",Territorial,Salud y Protección Social,Corporación Autónoma,Centralizada,CO1.BDOS.5361305,...,No definido,No definido,No definido,No definido,No definido,No,No definido,NaN,NaN,NaN
1,EMPRESA SOCIAL DEL ESTADO HOSPITAL LOCAL DE SA...,892000458,Meta,San Martín,"Colombia, Meta , San Martín",Nacional,Salud y Protección Social,Ejecutivo,Centralizada,CO1.BDOS.5360886,...,No definido,No definido,No definido,No definido,No definido,No,No definido,NaN,NaN,NaN
2,Ese Centro de Salud San Miguel,900135676,Nariño,Arboleda,"Colombia, Nariño , Arboleda",Territorial,Salud y Protección Social,Corporación Autónoma,Centralizada,CO1.BDOS.5359880,...,No definido,No definido,No definido,No definido,No definido,No,No definido,NaN,NaN,NaN
3,EMPRESA SOCIAL DEL ESTADO HOSPITAL DIVINO NIÑO,813002933,Huila,Rivera,"Colombia, Huila , Rivera",Territorial,Salud y Protección Social,Corporación Autónoma,Descentralizada,CO1.BDOS.5362023,...,Cédula de Ciudadanía,1081152775,No definido,No definido,No definido,No,No definido,2024-04-01T00:00:00.000,2024-06-30T00:00:00.000,NaN
4,HOSPITAL DEPARTAMENTAL UNIVERSITARIO SANTA SOF...,890801099,Caldas,Manizales,"Colombia, Caldas , Manizales",Territorial,Salud y Protección Social,Ejecutivo,Centralizada,CO1.BDOS.5356278,...,No definido,No definido,No definido,No definido,No definido,No,No definido,2025-01-01T00:00:00.000,2025-03-20T00:00:00.000,NaN

In [6]:
df.columns

Index(['nombre_entidad', 'nit_entidad', 'departamento', 'ciudad',
       'localizaci_n', 'orden', 'sector', 'rama', 'entidad_centralizada',
       'proceso_de_compra', 'id_contrato', 'referencia_del_contrato',
       'estado_contrato', 'codigo_de_categoria_principal',
       'descripcion_del_proceso', 'tipo_de_contrato',
       'modalidad_de_contratacion', 'justificacion_modalidad_de',
       'fecha_de_firma', 'fecha_de_inicio_del_contrato',
       'fecha_de_fin_del_contrato', 'condiciones_de_entrega',
       'tipodocproveedor', 'documento_proveedor', 'proveedor_adjudicado',
       'es_grupo', 'es_pyme', 'habilita_pago_adelantado', 'liquidaci_n',
       'obligaci_n_ambiental', 'obligaciones_postconsumo', 'reversion',
       'origen_de_los_recursos', 'destino_gasto', 'valor_del_contrato',
       'valor_de_pago_adelantado', 'valor_facturado',
       'valor_pendiente_de_pago', 'valor_pagado', 'valor_amortizado',
       'valor_pendiente_de', 'valor_pendiente_de_ejecucion', 'saldo_cdp',
       'saldo_vigencia', 'espostconflicto', 'dias_adicionados',
       'puntos_del_acuerdo', 'pilares_del_acuerdo', 'urlproceso',
       'nombre_representante_legal', 'nacionalidad_representante_legal',
       'domicilio_representante_legal',
       'tipo_de_identificaci_n_representante_legal',
       'identificaci_n_representante_legal', 'g_nero_representante_legal',
       'presupuesto_general_de_la_nacion_pgn',
       'sistema_general_de_participaciones', 'sistema_general_de_regal_as',
       'recursos_propios_alcald_as_gobernaciones_y_resguardos_ind_genas_',
       'recursos_de_credito', 'recursos_propios', 'ultima_actualizacion',
       'codigo_entidad', 'codigo_proveedor', 'objeto_del_contrato',
       'duraci_n_del_contrato', 'nombre_del_banco', 'tipo_de_cuenta',
       'n_mero_de_cuenta', 'el_contrato_puede_ser_prorrogado',
       'nombre_ordenador_del_gasto', 'tipo_de_documento_ordenador_del_gasto',
       'n_mero_de_documento_ordenador_del_gasto', 'nombre_supervisor',
       'tipo_de_documento_supervisor', 'n_mero_de_documento_supervisor',
       'nombre_ordenador_de_pago', 'tipo_de_documento_ordenador_de_pago',
       'n_mero_de_documento_ordenador_de_pago', 'documentos_tipo',
       'descripcion_documentos_tipo', 'fecha_inicio_liquidacion',
       'fecha_fin_liquidacion', 'fecha_de_notificaci_n_de_prorrogaci_n'],
      dtype='object')

In [9]:
columns = ['nombre_entidad','nit_entidad','departamento','ciudad','orden','sector','rama','fecha_de_firma','fecha_de_inicio_del_contrato','fecha_de_fin_del_contrato','fecha_inicio_liquidacion','fecha_fin_liquidacion']

In [160]:
total_null = df.isnull().sum()
total_row = df.shape[0]

In [161]:
total_null_percentage = (total_null / total_row) * 100

In [162]:
total_null_percentage.loc[total_null_percentage >0]

referencia_del_contrato                   0.000053
fecha_de_inicio_del_contrato              0.753949
fecha_de_fin_del_contrato                 0.000053
documento_proveedor                       0.000685
proveedor_adjudicado                      0.000685
nacionalidad_representante_legal          0.000527
domicilio_representante_legal             0.003634
identificaci_n_representante_legal        0.000105
ultima_actualizacion                     18.075649
codigo_proveedor                          4.165543
objeto_del_contrato                       8.704190
duraci_n_del_contrato                     4.538963
nombre_del_banco                          0.000421
tipo_de_cuenta                            0.000369
n_mero_de_cuenta                          0.000474
el_contrato_puede_ser_prorrogado          2.544267
nombre_ordenador_del_gasto                4.837920
descripcion_documentos_tipo              17.426812
fecha_inicio_liquidacion                 74.595984
fecha_fin_liquidacion                    80.776287
fecha_de_notificaci_n_de_prorrogaci_n    89.956218
dtype: float64

In [13]:
df['estado_contrato'].value_counts()

estado_contrato
Cerrado         306185
En ejecución    272400
Modificado      152649
terminado       139380
Aprobado          7003
cedido            3545
Suspendido         816
Cancelado            6
Borrador             2
Name: count, dtype: int64

In [ ]:
def remove_accents(text):
    if isinstance(text, str):
        return unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('utf-8')
    return text

def clean_text(series):
    return series.apply(remove_accents).str.upper().str.strip('*/+-.,;:()[] ')

df['ciudad'] = clean_text(df['ciudad'])
df['departamento'] = clean_text(df['departamento'])

df['nombre_entidad'] = clean_text(df['nombre_entidad'])
df['sector'] = clean_text(df['sector'])
df['rama'] = clean_text(df['rama'])
df['orden'] = clean_text(df['orden'])

df['estado_contrato'] = clean_text(df['estado_contrato'])
df['tipo_de_contrato'] = clean_text(df['tipo_de_contrato'])

df['tipodocproveedor'] = clean_text(df['tipodocproveedor'])
df['proveedor_adjudicado'] = clean_text(df['proveedor_adjudicado'])

In [3]:
df.loc[df['documento_proveedor'].isnull(), ['id_contrato','codigo_proveedor','tipodocproveedor', 'documento_proveedor', 'proveedor_adjudicado']]

,id_contrato,codigo_proveedor,tipodocproveedor,documento_proveedor,proveedor_adjudicado
433019,CO1.PCCNTR.6347699,CONSULTORIA DE DISEÑO DE ILUMINACION ESTADIO P...,Otro,NaN,CONSORCIO ILUMINACIÓN ESTADIO PALOGRANDE 2024
613752,CO1.PCCNTR.6665949,MANTENIMIENTO Y SOPORTE; RENOVACION DE CONTRAT...,Otro,NaN,RENOVACION CONTRATOS 2024
654361,CO1.PCCNTR.6704363,Contratar en nombre de la Nación - Consejo Sup...,Otro,NaN,UT TONERS MAXPRINTOTALY-2024
742387,CO1.PCCNTR.6596077,Interventoría para las obras de mejoramiento y...,Otro,NaN,ESPACIOS SAN ANTONIO-20005287
880361,CO1.PCCNTR.7166800,2026-08-01T00:00:00.000,Otro,NaN,UT FONDO C&A 2024
1417200,CO1.PCCNTR.7949280,731598876,Cédula de Ciudadanía,NaN,ANGIE ANDREA MAZO ECHAVARRIA
1511437,CO1.PCCNTR.8067441,732280011,Otro,NaN,CONSORCIO ALIMENTOS PARA LA NIÑEZ
1543826,CO1.PCCNTR.8149609,732122585,Otro,NaN,CONSORCIO CONEXIÓN EDUCATIVA
1847742,CO1.PCCNTR.8631938,INTERVENTORÍA A LA EJECUCIÓN DE LAS OBRAS Y AC...,Otro,NaN,C CONSERVACIÓN VIAL CDG
1848471,CO1.PCCNTR.8579436,MANTENIMIENTO; ADECUACIÓN Y REHABILITACIÓN DE ...,Otro,NaN,CONSORCIO OBRAS CIVIL 2025
1889630,CO1.PCCNTR.8697098,CONSTRUCCIÓN DE LA PRIMERA FASE DE LAS OBRAS D...,Otro,NaN,CONSORCIO SANTOS 2025
1890850,CO1.PCCNTR.8719612,OBRAS COMPLEMENTARIAS Y DEMÁS ACTIVIDADES NECE...,Otro,NaN,CONSORCIO MARVALL
1892747,CO1.PCCNTR.8730416,REALIZAR EL RECONOCIMIENTO TECNICO Y EJECUCION...,Otro,NaN,CONSORCIO HDCIVILNET

In [4]:
df['codigo_proveedor'].unique()

array([719294506, 720225374, 724132030, ...,
       'Generar estrategias que impulsen la reindustrialización del país a través de los minerales estratégicos; mediante la divulgación y promoción de la política minera.',
       'COMPRA DE EQUIPOS DE COMPUTO Y ELEMENTOS TEGNOLOGICOS PARA EL FORTALECIMIENTO DE LAS LABORES DE LA PERSONERIA MUNICIPAL DE FOSCA CUNDINAMARCA',
       'PRESTAR SERVICIOS PROFESIONALES PARA ATENDER LOS ASUNTOS DE CARÁCTER SOCIAL DE LA INFRAESTRUCTURA VIAL; QUE SE DERIVA DE LOS PROGRAMAS; PROYECTOS; CONTRATOS Y/O CONVENIOS DESDE DE LA DIRECCIÓN TERRITORIAL SANTANDER DEL INSTITUTO NACIONAL DE VÍAS - INVIAS'],
      shape=(1130460,), dtype=object)

In [26]:
df.loc[df['codigo_proveedor'] == 706504313, ['descripcion_del_proceso','codigo_proveedor','id_contrato', 'nombre_entidad', 'proveedor_adjudicado', 'fecha_de_firma', 'departamento','nit_entidad', 'valor_del_contrato']]

,descripcion_del_proceso,codigo_proveedor,id_contrato,nombre_entidad,proveedor_adjudicado,fecha_de_firma,departamento,nit_entidad,valor_del_contrato
30,CONTRATAR EL SUMINISTRO Y DISPENSACIÓN DE MEDI...,706504313,CO1.PCCNTR.5707497,HOSPITAL SAN RAFAEL DE EL ESPINAL TOLIMA E.S.E,COODESTOL,2024-01-01T00:00:00.000,Tolima,890701033,53000000
280,CONTRATAR EL SUMINISTRO; DISTRIBUCIÓN; DISPENS...,706504313,CO1.PCCNTR.5707498,HOSPITAL SAN RAFAEL DE EL ESPINAL TOLIMA E.S.E,COODESTOL,2024-01-01T00:00:00.000,Tolima,890701033,330000000
4674,COMPRA; DISTRIBUCIÓN; SUMINISTRO; DISPENSACIÓN...,706504313,CO1.PCCNTR.5709420,HOSPITAL ESPECIALIZADO GRANJA INTEGRAL EMPRESA...,COODESTOL,2024-01-04T00:00:00.000,Tolima,800116719,32000000
5808,CONTRATAR EL SUMINISTRO DE MEDICAMENTOS INSUMO...,706504313,CO1.PCCNTR.5715738,HOSPITAL SAN JUAN DE DIOS EMPRESA SOCIAL DEL E...,COODESTOL,2024-01-05T00:00:00.000,Tolima,800163519,39000000
5865,CONTRATAR EL SUMINISTRO DE MEDICAMENTOS; MATE...,706504313,CO1.PCCNTR.5715392,CENTRAL DE URGENCIAS LOUIS PASTEUR E.S.E,COODESTOL,2024-01-05T00:00:00.000,Tolima,890702369,120000000
...,...,...,...,...,...,...,...,...,...
1635645,SUMINISTRO DE MATERIAL MEDICO QUIRURGICO PARA ...,706504313,CO1.PCCNTR.8302954,HOSPITAL SAN JUAN DE DIOS DE HONDA ESE,COODESTOL,2025-09-09T00:00:00.000,Tolima,890700666,459921278
1643335,SUMINISTRO DE MEDICAMENTOS; ELEMENTOS MÉDICO Q...,706504313,CO1.PCCNTR.8303979,HOSPITAL SAN CARLOS ESE SALDAÑA,COODESTOL,2025-09-11T00:00:00.000,Tolima,890701300,35000000
1645598,CONTRATAR A MONTO AGOTABLE EL SUMINISTRO DE RE...,706504313,CO1.PCCNTR.8318559,UNIDAD DE SALUD DE IBAGUE U.S.I. - E.S.E.,COODESTOL,2025-09-12T00:00:00.000,Tolima,809003590,453119012
1717003,CONTRATAR EL SUMINISTRO DE MEDICAMENTOS; MATE...,706504313,CO1.PCCNTR.8430607,CENTRAL DE URGENCIAS LOUIS PASTEUR E.S.E,COODESTOL,2025-10-08T00:00:00.000,Tolima,890702369,150000000
1725507,SUMINISTRO DE MEDICAMENTOS; DISPOSITIVOS MÉDIC...,706504313,CO1.PCCNTR.8276673,HOSMI,COODESTOL,2025-10-11T00:00:00.000,Tolima,8907006944,80000000

In [12]:
mask = pd.to_numeric(df['codigo_proveedor'], errors='coerce').isna()

In [31]:
df.loc[mask, ['id_contrato','codigo_proveedor','tipodocproveedor', 'documento_proveedor', 'proveedor_adjudicado']]

,id_contrato,codigo_proveedor,tipodocproveedor,documento_proveedor,proveedor_adjudicado
150000,CO1.PCCNTR.5932776,PRESTAR SERVICIOS PROFESIONALES COMO CONTADOR ...,Cédula de Ciudadanía,79610256,CARLOS MARTINEZ
150001,CO1.PCCNTR.5931387,Prestar servicios profesionales al Fondo para ...,Cédula de Ciudadanía,1010224737,FELIPE QUEVEDO
150002,CO1.PCCNTR.5931366,PRESTACION DE LOS SERVICIOS PROFESIONALES COMO...,Cédula de Ciudadanía,91105411,FABIO GUTIERREZ MARIN
150003,CO1.PCCNTR.5931916,PRESTAR SERVICIOS DE APOYO A LA GESTIÓN; PARA ...,Cédula de Ciudadanía,52782796,ANNIE RITA ALVAREZ PACHECO
150004,CO1.PCCNTR.5914740,Suministro de materiales e insumos de oficina ...,Cédula de Ciudadanía,1085634356,SONIA ALEJANDRA MONTENEGRO NASTAR
...,...,...,...,...,...
1898931,CO1.PCCNTR.8743449,COMPRA DE EQUIPOS DE COMPUTO Y ELEMENTOS TEGNO...,NIT,901463618,CONSTRUYE VERDE PROYECTOS Y SUMINISTROS SAS
1898932,CO1.PCCNTR.8748921,PRESTAR LOS SERVICIOS DE EDUCACIÓN INICIAL EN ...,NIT,800072361,ASOCIACION DE PADRES DE HOGARES DE BIENESTAR S...
1898933,CO1.PCCNTR.8734716,ADQUISICIÓN DE ELEMENTOS TIPOS CONSUMIBLES TAL...,NIT,860053274,GRUPO LOS LAGOS SAS
1898934,CO1.PCCNTR.8746765,PRESTAR SERVICIOS PROFESIONALES PARA ATENDER L...,Cédula de Ciudadanía,1094808521,MARTHA YANETH LIZCANO BAUTISTA
1898935,CO1.PCCNTR.8749527,PRESTAR LOS SERVICIOS DE EDUCACIÓN INICIAL EN ...,NIT,8210022337,ASOCIACION DE COMUNIDADES AFROCOLOMBIANAS DEL ...

In [15]:
df['documento_proveedor'].duplicated().sum()

np.int64(1171465)

In [13]:
mask.sum()

np.int64(948919)

#Table Localitation

In [93]:
location = df[['ciudad','departamento']]

In [23]:
len(location)

1898936

In [68]:
location.value_counts()

city           department  id_location
TIMBIO         CAUCA       1              1
SAN MARTIN     META        2              1
ARBOLEDA       NARINO      3              1
RIVERA         HUILA       4              1
MANIZALES      CALDAS      5              1
                                         ..
CUNDAY         TOLIMA      901            1
SAN SEBASTIAN  CAUCA       902            1
LA FLORIDA     NARINO      903            1
URAMITA        ANTIOQUIA   904            1
LA CRUZ        NARINO      905            1
Name: count, Length: 905, dtype: int64

In [94]:
location.drop_duplicates(inplace=True)
location.reset_index(drop=True, inplace=True)

In [70]:
len(location)

905

In [95]:
location['id_location'] = range(1,len(location)+1)

In [96]:
location.head()

       ciudad departamento  id_location
0      TIMBIO        CAUCA            1
1  SAN MARTIN         META            2
2    ARBOLEDA       NARINO            3
3      RIVERA        HUILA            4
4   MANIZALES       CALDAS            5

In [6]:
location.loc[location['departamento'] == 'Distrito Capital de Bogotá', ['departamento', 'ciudad']]

                   departamento            ciudad
48   Distrito Capital de Bogotá       No Definido
53   Distrito Capital de Bogotá            Bogotá
262  Distrito Capital de Bogotá  Distrito Capital

In [97]:
location.rename(columns={'ciudad': 'city', 'departamento': 'department'}, inplace=True)

In [98]:
location.head()

         city department  id_location
0      TIMBIO      CAUCA            1
1  SAN MARTIN       META            2
2    ARBOLEDA     NARINO            3
3      RIVERA      HUILA            4
4   MANIZALES     CALDAS            5

In [77]:
location.loc[location['city'].str.contains('M'),:]

                    city department  id_location
0                 TIMBIO      CAUCA            1
1             SAN MARTIN       META            2
4              MANIZALES     CALDAS            5
7                ARMENIA    QUINDIO            8
9               PIENDAMO      CAUCA           10
..                   ...        ...          ...
880          MARQUETALIA     CALDAS          881
881               SACAMA   CASANARE          882
882              MALLAMA     NARINO          883
890  EL CARMEN DE ATRATO      CHOCO          891
903              URAMITA  ANTIOQUIA          904

[198 rows x 3 columns]

In [78]:
location['department'].duplicated().sum()

np.int64(871)

In [99]:
len(location)

905

#Table entity

In [100]:
entity = df[['nombre_entidad','nit_entidad','orden','sector','rama', 'ciudad','departamento']]

In [101]:
entity.rename(columns={'ciudad': 'city', 'departamento': 'department','nombre_entidad':'name_entity','nit_entidad':'nit_entity','orden':'order_entity','rama':'branch_entity','sector':'sector_entity'}, inplace=True)

In [102]:
len(entity)

1898936

In [103]:
entity.drop_duplicates(inplace=True)

In [104]:
len(entity)

4373

In [105]:
entity = entity.merge(location, on=['city','department'], how='left')

In [106]:
entity.drop(columns=['city','department'], inplace=True)

In [107]:
entity.head()

,name_entity,nit_entity,order_entity,sector_entity,branch_entity,id_location
0,HOSPITAL TIMBIO ESE,817000999,TERRITORIAL,SALUD Y PROTECCION SOCIAL,CORPORACION AUTONOMA,1
1,EMPRESA SOCIAL DEL ESTADO HOSPITAL LOCAL DE SA...,892000458,NACIONAL,SALUD Y PROTECCION SOCIAL,EJECUTIVO,2
2,ESE CENTRO DE SALUD SAN MIGUEL,900135676,TERRITORIAL,SALUD Y PROTECCION SOCIAL,CORPORACION AUTONOMA,3
3,EMPRESA SOCIAL DEL ESTADO HOSPITAL DIVINO NINO,813002933,TERRITORIAL,SALUD Y PROTECCION SOCIAL,CORPORACION AUTONOMA,4
4,HOSPITAL DEPARTAMENTAL UNIVERSITARIO SANTA SOF...,890801099,TERRITORIAL,SALUD Y PROTECCION SOCIAL,EJECUTIVO,5

In [136]:
entity[['nit_entity','name_entity']].duplicated().sum()

np.int64(0)

In [128]:
entity.loc[entity['nit_entity'].duplicated(keep=False), ['name_entity','nit_entity','id_location','order_entity','branch_entity','sector_entity']]

,name_entity,nit_entity,id_location,order_entity,branch_entity,sector_entity
25,MUNICIPIO DE ITAGUI,890980093,23,TERRITORIAL,EJECUTIVO,"VIVIENDA, CIUDAD Y TERRITORIO"
30,MUNICIPIO DE ENVIGADO,890907106,27,NACIONAL,EJECUTIVO,CULTURA
72,ALCALDIA LOCAL DE SAN CRISTOBAL,899999061,54,TERRITORIAL,EJECUTIVO,SERVICIO PUBLICO
96,DEPARTAMENTO DE ANTIOQUIA,890900286,22,TERRITORIAL,EJECUTIVO,SERVICIO PUBLICO
139,INSTITUTO COLOMBIANO AGROPECUARIO - ICA,899999069,54,NACIONAL,EJECUTIVO,AGRICULTURA
...,...,...,...,...,...,...
4343,CONCEJO MUNICIPAL DE PIENDAMO TUNIA,891500856,10,TERRITORIAL,EJECUTIVO,NO APLICA/NO PERTENECE
4347,CONCEJO MUNICIPAL RIOSUCIO CALDAS,890801138,18,TERRITORIAL,LEGISLATIVO,NO APLICA/NO PERTENECE
4352,CONCEJO MUNICIPAL DE TIMANA,891180182,260,TERRITORIAL,LEGISLATIVO,SERVICIO PUBLICO
4358,PERSONERIA MUNICIPAL DE SOATA,891855016,353,TERRITORIAL,CORPORACION AUTONOMA,NO APLICA/NO PERTENECE
4368,ARMADA NACIONAL JEFATURA DE DESARROLO HUMANO Y...,800141644,54,NACIONAL,EJECUTIVO,DEFENSA

In [142]:
entity.loc[entity['nit_entity'] == 899999034, :]

,name_entity,nit_entity,order_entity,sector_entity,branch_entity,id_location
495,SENA REGIONAL SANTANDER GRUPO DE APOYO ADMINIS...,899999034,NACIONAL,TRABAJO,EJECUTIVO,52
520,SENA REGIONAL SANTANDER GRUPO ADMINISTRATIVO CA,899999034,NACIONAL,TRABAJO,EJECUTIVO,40
528,SENA SECRETARIA GENERAL,899999034,NACIONAL,TRABAJO,EJECUTIVO,49
536,SENA REGIONAL TOLIMA 1,899999034,NACIONAL,TRABAJO,EJECUTIVO,115
594,SENA REGIONAL RISARALDA GRUPO DE APOYO ADMINIS...,899999034,NACIONAL,EDUCACION NACIONAL,EJECUTIVO,60
...,...,...,...,...,...,...
1242,CENTRO DE COMERCIO Y SERVICIOS - SENA REGIONAL...,899999034,NACIONAL,TRABAJO,EJECUTIVO,16
1843,SENA DIRECCION GENERAL,899999034,NACIONAL,TRABAJO,EJECUTIVO,54
2075,SENA DIRECCION GENERAL DIRECCION DE PROMOCION ...,899999034,NACIONAL,TRABAJO,EJECUTIVO,54
2158,SENA PUERTO BOYACA,899999034,NACIONAL,EDUCACION NACIONAL,EJECUTIVO,385
2375,SENA REGIONAL BOYACA GRUPO ADMINISTRATIVO CGAFE,899999034,NACIONAL,TRABAJO,EJECUTIVO,34

In [125]:
location.loc[location['id_location'] == 529, :]

        city department  id_location
528  MURILLO     TOLIMA          529

In [115]:
duplicated = entity.groupby('nit_entity')['name_entity'].nunique()

In [141]:
duplicated[duplicated > 1].sort_values(ascending=False)

nit_entity
899999034     80
899999061     34
899999239     32
899999067     31
899999069     29
              ..
8909073172     2
800097180      2
800095461      2
800099317      2
800099310      2
Name: name_entity, Length: 263, dtype: int64

In [37]:
entity['nit_entidad'].dtype

dtype('int64')

In [143]:
entity['id_entity'] = range(1,len(entity)+1)

In [144]:
entity.head()

,name_entity,nit_entity,order_entity,sector_entity,branch_entity,id_location,id_entity
0,HOSPITAL TIMBIO ESE,817000999,TERRITORIAL,SALUD Y PROTECCION SOCIAL,CORPORACION AUTONOMA,1,1
1,EMPRESA SOCIAL DEL ESTADO HOSPITAL LOCAL DE SA...,892000458,NACIONAL,SALUD Y PROTECCION SOCIAL,EJECUTIVO,2,2
2,ESE CENTRO DE SALUD SAN MIGUEL,900135676,TERRITORIAL,SALUD Y PROTECCION SOCIAL,CORPORACION AUTONOMA,3,3
3,EMPRESA SOCIAL DEL ESTADO HOSPITAL DIVINO NINO,813002933,TERRITORIAL,SALUD Y PROTECCION SOCIAL,CORPORACION AUTONOMA,4,4
4,HOSPITAL DEPARTAMENTAL UNIVERSITARIO SANTA SOF...,890801099,TERRITORIAL,SALUD Y PROTECCION SOCIAL,EJECUTIVO,5,5

#Table provider

In [16]:
provider = df[['codigo_proveedor','proveedor_adjudicado','documento_proveedor', 'es_pyme','tipodocproveedor']]

In [17]:
provider.rename(columns={'codigo_proveedor':'id_provider','proveedor_adjudicado':'name_provider','documento_proveedor':'provider_document','es_pyme':'is_pyme','tipodocproveedor':'type_of_provider'}, inplace=True)

In [18]:
provider.drop_duplicates(inplace=True)

In [19]:
provider.head()

,id_provider,name_provider,provider_document,is_pyme,type_of_provider
0,719294506,SANDRA LILIANA CLAVIJO MOLINA,34658915,No,Cédula de Ciudadanía
1,720225374,LISBETH DAYELLI ROZO SALDAÑA,1073719989,No,Cédula de Ciudadanía
2,724132030,LUISA MARIA BENAVIDES VERGARA,1085329201,No,Cédula de Ciudadanía
3,724422027,MARIA CAMILA VARON CALDERON,1053818566,No,Cédula de Ciudadanía
4,720324235,KEVIN FERNANDO MONTOYA QUINTERO,16073507,No,Cédula de Ciudadanía

In [20]:
provider['id_provider'].duplicated().sum()

np.int64(333620)

In [33]:
df.loc[df['codigo_proveedor'].isnull(), ['id_contrato','codigo_proveedor','tipodocproveedor', 'documento_proveedor', 'proveedor_adjudicado']]

,id_contrato,codigo_proveedor,tipodocproveedor,documento_proveedor,proveedor_adjudicado
850001,CO1.PCCNTR.7102516,NaN,NIT,901895351,CONSORCIO REDISEÑO INSTITUCIONAL P&S 2024
850002,CO1.PCCNTR.7103813,NaN,Cédula de Ciudadanía,1031144800,Andres Felipe Betancur Hernandez
850003,CO1.PCCNTR.7114668,NaN,Cédula de Ciudadanía,94487958,JOHN JAIRO SANTAMARIA CAMPO
850004,CO1.PCCNTR.7098710,NaN,Cédula de Ciudadanía,39045700,PETRONA MARIA CABARCAS BARRIOS
850005,CO1.PCCNTR.7119854,NaN,Cédula de Ciudadanía,1113656604,Nery Alexandra Mendoza Hoyos
...,...,...,...,...,...
1799994,CO1.PCCNTR.8519157,NaN,Cédula de Ciudadanía,1007475990,Maria Camila Guaqueta Ruiz
1799996,CO1.PCCNTR.8544115,NaN,Cédula de Ciudadanía,1001867050,Jeider Berdugo Piñeres
1799997,CO1.PCCNTR.8566320,NaN,Cédula de Ciudadanía,66701505,ARGENIS OSPINA MARIN
1799998,CO1.PCCNTR.8558754,NaN,Cédula de Ciudadanía,60442386,MARISOL MARTINEZ MEJIA
1799999,CO1.PCCNTR.8570214,NaN,Cédula de Ciudadanía,31866882,PATRICIA BOTERO MEJIA

In [34]:
provider.loc[provider['id_provider'] == 729420026, ['id_provider','name_provider','provider_document','is_pyme','type_of_provider']]

Empty DataFrame
Columns: [id_provider, name_provider, provider_document, is_pyme, type_of_provider]
Index: []

In [155]:
provider['provider_document'].isnull().sum()

np.int64(8150)

In [156]:
provider.loc[provider['name_provider'].isnull(), :]

,id_provider,name_provider,provider_document,is_pyme,type_of_provider
287283,PRESTACIÓN DE SERVICIOS DE APOYO A LA GESTIÓN ...,NaN,64521672,No,CEDULA DE CIUDADANIA
577200,727754780,NaN,1085636247,No,CEDULA DE CIUDADANIA
692296,EL CONTRATISTA se obliga con RTVC a prestar su...,NaN,79123979,No,CEDULA DE CIUDADANIA
799565,727754780,NaN,1085636247,No,CEDULA DE CIUDADANIA
807550,PRESTACIÓN DE SERVICIOS COMO GUARDIÁN AUXILIAR...,NaN,1000352981,No,CEDULA DE CIUDADANIA
1236156,725724496,NaN,79123979,No,CEDULA DE CIUDADANIA
1343978,PRESTACIÓN DE SERVICIOS DE APOYO A LA GESTIÓN ...,NaN,64521672,No,CEDULA DE CIUDADANIA
1365550,Prestar servicios de apoyo a la gestion admini...,NaN,52707924,No,CEDULA DE CIUDADANIA
1579642,CONTRATAR LA PRESTACION DEL SERVICIO DE UN AUX...,NaN,1110487136,No,TARJETA DE IDENTIDAD
1595871,PRESTACIÓN DE SERVICIOS PROFESIONALES PARA PSI...,NaN,1085636247,No,CEDULA DE CIUDADANIA
1883770,Prestar sus servicios como apoyo logístico par...,NaN,79123979,No,CEDULA DE CIUDADANIA

In [157]:
provider['id_provider'].dtype

dtype('O')

In [26]:
provider.loc[provider['is_pyme'] == 'Si','is_pyme'] = True
provider.loc[provider['is_pyme'] == 'No', 'is_pyme'] = False

In [27]:
provider.head()

,id_provider,name_provider,provider_document,is_pyme,type_of_provider
0,719294506,SANDRA LILIANA CLAVIJO MOLINA,34658915,False,Cédula de Ciudadanía
1,720225374,LISBETH DAYELLI ROZO SALDAÑA,1073719989,False,Cédula de Ciudadanía
2,724132030,LUISA MARIA BENAVIDES VERGARA,1085329201,False,Cédula de Ciudadanía
3,724422027,MARIA CAMILA VARON CALDERON,1053818566,False,Cédula de Ciudadanía
4,720324235,KEVIN FERNANDO MONTOYA QUINTERO,16073507,False,Cédula de Ciudadanía

#Table dim_date

In [92]:
dim_date = pd.concat([df['fecha_de_inicio_del_contrato'], df['fecha_de_fin_del_contrato'], df['fecha_de_firma'], df['fecha_inicio_liquidacion'], df['fecha_fin_liquidacion']])

In [93]:
date = pd.DataFrame(dim_date.drop_duplicates().dropna().reset_index(drop=True), columns=['date'])

In [94]:
date['date'] = pd.to_datetime(date['date'], format='ISO8601', errors='coerce')

In [95]:
df.loc[df['fecha_de_fin_del_contrato'] >= '2100-01-01T00:00:00.000', ['fecha_de_inicio_del_contrato', 'fecha_de_fin_del_contrato','estado_contrato','nombre_entidad','proveedor_adjudicado','valor_del_contrato']]

,fecha_de_inicio_del_contrato,fecha_de_fin_del_contrato,estado_contrato,nombre_entidad,proveedor_adjudicado,valor_del_contrato
242891,2024-03-12T00:00:00.000,2924-12-31T00:00:00.000,Modificado,MINISTERIO DE MINAS Y ENERGIA,Marcia Lorena Parra Velásquez,107800000
328355,2024-04-17T00:00:00.000,2924-08-12T00:00:00.000,En ejecución,MUNICIPIO DE PRADERA,Yessica Maria Amezquita Romero,9800000

In [96]:
date = date.drop_duplicates()

In [97]:
date.dropna(inplace=True)

In [98]:
date.head()

        date
0 2024-01-01
1 2024-01-02
2 2024-01-05
3 2024-01-03
4 2024-03-01

In [99]:
date['year'] = date['date'].dt.year.astype('Int64')
date['month'] = date['date'].dt.month.astype('Int64')
date['day'] = date['date'].dt.day.astype('Int64')
date['quarter'] = date['date'].dt.quarter.astype('Int64')
date['week'] = date['date'].dt.isocalendar().week.astype('Int64')
date['day_of_week'] = date['date'].dt.dayofweek.astype('Int64')
date['day_name'] = date['date'].dt.day_name()
date['month_name'] = date['date'].dt.month_name()
date['is_weekend'] = date['day_of_week'].isin([5, 6])

In [100]:
date['id_date'] = date['date'].dt.strftime('%Y%m%d').astype('Int64')

In [101]:
date.head()

,date,year,month,day,quarter,week,day_of_week,day_name,month_name,is_weekend,id_date
0,2024-01-01,2024,1,1,1,1,0,Monday,January,False,20240101
1,2024-01-02,2024,1,2,1,1,1,Tuesday,January,False,20240102
2,2024-01-05,2024,1,5,1,1,4,Friday,January,False,20240105
3,2024-01-03,2024,1,3,1,1,2,Wednesday,January,False,20240103
4,2024-03-01,2024,3,1,1,9,4,Friday,March,False,20240301

In [102]:
date.isnull().sum()

date           0
year           0
month          0
day            0
quarter        0
week           0
day_of_week    0
day_name       0
month_name     0
is_weekend     0
id_date        0
dtype: int64

#table contract

In [103]:
contract = df[['id_contrato','codigo_entidad','codigo_proveedor','fecha_de_inicio_del_contrato',
               'fecha_de_fin_del_contrato','fecha_de_firma','fecha_inicio_liquidacion','fecha_fin_liquidacion',
               'estado_contrato','valor_del_contrato','valor_pendiente_de_pago','valor_pagado','tipo_de_contrato',
               'liquidaci_n','obligaci_n_ambiental','espostconflicto']]

In [115]:
contract.head()

,id_contract,id_entity,id_provider,id_contract_start_date,id_contract_end_date,id_signing_date,id_liquidation_start_date,id_liquidation_end_date,contract_state,contract_value,pending_payment_amount,paid_amount,contract_type,liquidation,environmental_obligation,is_post_conflict
0,CO1.PCCNTR.5707540,710500463,719294506,20240101,20240930,20240101,<NA>,<NA>,Modificado,24341985,24341985,0,Decreto 092 de 2017,False,False,False
1,CO1.PCCNTR.5707355,705985851,720225374,20240101,20240131,20240101,<NA>,<NA>,terminado,1730400,1730400,0,Prestación de servicios,False,False,False
2,CO1.PCCNTR.5707810,716359328,724132030,20240102,20240229,20240101,<NA>,<NA>,En ejecución,4400000,4400000,0,Prestación de servicios,False,False,False
3,CO1.PCCNTR.5707593,714657632,724422027,20240101,20240331,20240101,20240401,20240630,Modificado,19474560,3951360,15523200,Prestación de servicios,True,False,False
4,CO1.PCCNTR.5705140,704527647,720324235,20240101,20241231,20240101,20250101,20250320,Cerrado,190000000,190000000,0,Prestación de servicios,True,False,False

In [108]:
contract.rename(columns={'id_contrato':'id_contract','codigo_entidad':'id_entity','codigo_proveedor':'id_provider','fecha_de_inicio_del_contrato':'id_contract_start_date',
                         'fecha_de_fin_del_contrato':'id_contract_end_date','fecha_de_firma':'id_signing_date','fecha_inicio_liquidacion':'id_liquidation_start_date','fecha_fin_liquidacion':'id_liquidation_end_date',
                         'estado_contrato':'contract_state','valor_del_contrato':'contract_value','valor_pendiente_de_pago':'pending_payment_amount','valor_pagado':'paid_amount','tipo_de_contrato':'contract_type','liquidaci_n':'liquidation','obligaci_n_ambiental':'environmental_obligation','espostconflicto':'is_post_conflict'}, inplace=True)

C:\Users\bryan\AppData\Local\Temp\ipykernel_8232\1383937006.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  contract.rename(columns={'id_contrato':'id_contract','codigo_entidad':'id_entity','codigo_proveedor':'id_provider','fecha_de_inicio_del_contrato':'id_contract_start_date',

In [110]:
contract['id_contract_start_date'] = pd.to_datetime(contract['id_contract_start_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')

contract['id_contract_end_date'] = pd.to_datetime(contract['id_contract_end_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')

contract['id_signing_date'] = pd.to_datetime(contract['id_signing_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')

contract['id_liquidation_start_date'] = pd.to_datetime(contract['id_liquidation_start_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')

contract['id_liquidation_end_date'] = pd.to_datetime(contract['id_liquidation_end_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')

C:\Users\bryan\AppData\Local\Temp\ipykernel_8232\1399252456.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  contract['id_contract_start_date'] = pd.to_datetime(contract['id_contract_start_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')
C:\Users\bryan\AppData\Local\Temp\ipykernel_8232\1399252456.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  contract['id_contract_end_date'] = pd.to_datetime(contract['id_contract_end_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')
C:\Users\bryan\AppData\Local\Temp\ipykernel_8232\1399252456.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  contract['id_signing_date'] = pd.to_datetime(contract['id_signing_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')
C:\Users\bryan\AppData\Local\Temp\ipykernel_8232\1399252456.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  contract['id_liquidation_start_date'] = pd.to_datetime(contract['id_liquidation_start_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')
C:\Users\bryan\AppData\Local\Temp\ipykernel_8232\1399252456.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  contract['id_liquidation_end_date'] = pd.to_datetime(contract['id_liquidation_end_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')

In [114]:
contract.loc[contract['liquidation'] == 'Si','liquidation'] = True
contract.loc[contract['liquidation'] == 'No', 'liquidation'] =  False

contract.loc[contract['environmental_obligation'] == 'Si','environmental_obligation'] = True
contract.loc[contract['environmental_obligation'] == 'No', 'environmental_obligation'] =  False

contract.loc[contract['is_post_conflict'] == 'Si','is_post_conflict'] = True
contract.loc[contract['is_post_conflict'] == 'No', 'is_post_conflict'] =  False

Analisis de calidad

In [246]:
entity['codigo_entidad'].duplicated().sum()

0

In [249]:
entity.loc[entity['nombre_entidad'].duplicated(keep=False),:]

,codigo_entidad,nombre_entidad,nit_entidad,orden,sector,rama,id_localitation
886,717160402,CENTRAL ADMINISTRATIVA Y CONTABLE - CENAC - AR...,901540882,Nacional,defensa,Ejecutivo,9
1768,702908666,CENTRAL ADMINISTRATIVA Y CONTABLE - CENAC - AR...,800130829,Nacional,defensa,Ejecutivo,9
2493,719986374,IPC,825001850,Territorial,Educación Nacional,Ejecutivo,75
2781,726067267,IPC,9018178262,Territorial,Servicio Público,Corporación Autónoma,41

In [119]:
contract['id_contract_end_date'].isnull().sum()

4