In [90]:
import pandas as pd
import unicodedata
import requests

In [100]:
columns = [
        # location
        'departamento', 'ciudad',

        # entity
        'codigo_entidad', 'nit_entidad', 'nombre_entidad', 'orden', 'sector', 'rama',

        # contract
        'id_contrato', 'estado_contrato', 'tipo_de_contrato', 'liquidaci_n', 'obligaci_n_ambiental',
        'espostconflicto', 'valor_del_contrato', 'valor_pendiente_de_pago', 'valor_pagado', 'entidad_centralizada',
        'modalidad_de_contratacion', 'origen_de_los_recursos', 'destino_gasto', 'habilita_pago_adelantado',
        'obligaciones_postconsumo', 'reversion', 'valor_de_pago_adelantado', 'valor_facturado', 'valor_amortizado',
        'valor_pendiente_de', 'valor_pendiente_de_ejecucion', 'dias_adicionados', 'duraci_n_del_contrato',
        'el_contrato_puede_ser_prorrogado',

        # provider
        'codigo_proveedor', 'tipodocproveedor', 'documento_proveedor', 'proveedor_adjudicado', 'es_pyme', 'es_grupo',

        # dates
        'fecha_de_firma', 'fecha_de_inicio_del_contrato', 'fecha_de_fin_del_contrato',
        'fecha_inicio_liquidacion', 'fecha_fin_liquidacion', 'ultima_actualizacion',
    ]

select_columns = [':id'] + columns  # pedimos también la columna de sistema

In [101]:
data = requests.get("https://www.datos.gov.co/resource/jbjy-vk9h.json", params={"$limit": 5, '$select': ','.join(select_columns), '$where': 'id_contrato = "CO1.PCCNTR.8033826"', '$order': 'id_contrato'}).json()

df = pd.DataFrame(data)

In [103]:
df.value_counts()

:id                 departamento  ciudad       codigo_entidad  nit_entidad  nombre_entidad       orden     sector                     rama       id_contrato         estado_contrato  tipo_de_contrato         liquidaci_n  obligaci_n_ambiental  espostconflicto  valor_del_contrato  valor_pendiente_de_pago  valor_pagado  entidad_centralizada  modalidad_de_contratacion      origen_de_los_recursos  destino_gasto  habilita_pago_adelantado  obligaciones_postconsumo  reversion  valor_de_pago_adelantado  valor_facturado  valor_amortizado  valor_pendiente_de  valor_pendiente_de_ejecucion  dias_adicionados  duraci_n_del_contrato  el_contrato_puede_ser_prorrogado  codigo_proveedor  tipodocproveedor  documento_proveedor  proveedor_adjudicado  es_pyme  es_grupo  fecha_de_fin_del_contrato
row-6at7-ryis_ff73  Huila         No Definido  704150309       899999239    ICBF REGIONAL HUILA  Nacional  Salud y Protección Social  Ejecutivo  CO1.PCCNTR.8033826  Cancelado        Prestación de servicios  No           No                    No               0                   3610000000000000000      0             Centralizada          Contratación régimen especial  Distribuido             Inversión      No                        No                        No         0                         0                0                 0                   0                             0                 5 Mes(es)              No                                704591783         NIT               813013679            CRIHU                 No       No        2025-11-30T00:00:00.000      1
Name: count, dtype: int64

In [96]:
data

[{':id': 'row-6at7-ryis_ff73',
  ':updated_at': '2026-07-11T09:14:23.301Z',
  'id_contrato': 'CO1.PCCNTR.8033826'}]

In [113]:
data = requests.get("https://www.datos.gov.co/resource/jbjy-vk9h.json", params={"$limit": 100, '$select': ','.join(select_columns), '$where': 'fecha_de_firma = "2023-01-17T00:00:00.000" and id_contrato = "CO1.PCCNTR.4385265"'}).json()

In [114]:
data

[{':id': 'row-ethb_r9qv_v3u5',
  'departamento': 'Magdalena',
  'ciudad': 'Santa Marta',
  'codigo_entidad': '705278133',
  'nit_entidad': '891780185',
  'nombre_entidad': 'ESE HOSPITAL UNIVERSITARIO JULIO MENDEZ BARRENECHE',
  'orden': 'Territorial',
  'sector': 'Salud y Protección Social',
  'rama': 'Ejecutivo',
  'id_contrato': 'CO1.PCCNTR.4385265',
  'estado_contrato': 'En ejecución',
  'tipo_de_contrato': 'Prestación de servicios',
  'liquidaci_n': 'No',
  'obligaci_n_ambiental': 'No',
  'espostconflicto': 'No',
  'valor_del_contrato': '3800000',
  'valor_pendiente_de_pago': '3800000',
  'valor_pagado': '0',
  'entidad_centralizada': 'Descentralizada',
  'modalidad_de_contratacion': 'Contratación régimen especial',
  'origen_de_los_recursos': 'Recursos Propios',
  'destino_gasto': 'Funcionamiento',
  'habilita_pago_adelantado': 'No',
  'obligaciones_postconsumo': 'No',
  'reversion': 'No',
  'valor_de_pago_adelantado': '0',
  'valor_facturado': '0',
  'valor_amortizado': '0',
  'valor_pendiente_de': '0',
  'valor_pendiente_de_ejecucion': '3800000',
  'dias_adicionados': '0',
  'duraci_n_del_contrato': '2 Mes(es)',
  'el_contrato_puede_ser_prorrogado': 'No',
  'codigo_proveedor': '718401490',
  'tipodocproveedor': 'Cédula de Ciudadanía',
  'documento_proveedor': '36721560',
  'proveedor_adjudicado': 'LORENA PATRICIA OROZCO VILLA',
  'es_pyme': 'No',
  'es_grupo': 'No',
  'fecha_de_firma': '2023-01-17T00:00:00.000',
  'fecha_de_inicio_del_contrato': '2023-01-19T00:00:00.000',
  'fecha_de_fin_del_contrato': '2023-02-28T00:00:00.000'}]

In [117]:
data = requests.get("https://www.datos.gov.co/resource/jbjy-vk9h.json", params={"$limit": 100, '$select': ':id,id_contrato', '$where': ':id = "row-ethb_r9qv_v3u5"'}).json()

In [118]:
data

[{':id': 'row-ethb_r9qv_v3u5', 'id_contrato': 'CO1.PCCNTR.4385265'}]

In [60]:
df.columns

Index([':id', 'departamento', 'ciudad', 'codigo_entidad', 'nit_entidad',
       'nombre_entidad', 'orden', 'sector', 'rama', 'id_contrato',
       'estado_contrato', 'tipo_de_contrato', 'liquidaci_n',
       'obligaci_n_ambiental', 'espostconflicto', 'valor_del_contrato',
       'valor_pendiente_de_pago', 'valor_pagado', 'entidad_centralizada',
       'modalidad_de_contratacion', 'origen_de_los_recursos', 'destino_gasto',
       'habilita_pago_adelantado', 'obligaciones_postconsumo', 'reversion',
       'valor_de_pago_adelantado', 'valor_facturado', 'valor_amortizado',
       'valor_pendiente_de', 'valor_pendiente_de_ejecucion',
       'dias_adicionados', 'duraci_n_del_contrato',
       'el_contrato_puede_ser_prorrogado', 'codigo_proveedor',
       'tipodocproveedor', 'documento_proveedor', 'proveedor_adjudicado',
       'es_pyme', 'es_grupo', 'fecha_de_firma', 'fecha_de_inicio_del_contrato',
       'fecha_de_fin_del_contrato'],
      dtype='str')

In [50]:
df[['ultima_actualizacion']]

KeyError: "None of [Index(['ultima_actualizacion'], dtype='str')] are in the [columns]"

In [15]:
df = pd.read_csv("../data/raw/secop2-26_0807.csv")

C:\Users\bryan\AppData\Local\Temp\ipykernel_9776\867413246.py:1: DtypeWarning: Columns (0: codigo_proveedor, 1: valor_de_pago_adelantado, 2: valor_facturado, 3: valor_amortizado) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raw/secop2-26_0807.csv")

In [ ]:
df['fecha_de_firma'].isnull().sum()

np.int64(1961657)

tamaño del csv

In [3]:
df.shape

(5265125, 51)

In [4]:
df.columns

Index(['departamento', 'ciudad', 'codigo_entidad', 'nit_entidad',
       'nombre_entidad', 'orden', 'sector', 'rama', 'id_contrato',
       'estado_contrato', 'tipo_de_contrato', 'liquidaci_n',
       'obligaci_n_ambiental', 'espostconflicto', 'valor_del_contrato',
       'valor_pendiente_de_pago', 'valor_pagado', 'codigo_proveedor',
       'tipodocproveedor', 'documento_proveedor', 'proveedor_adjudicado',
       'es_pyme', 'fecha_de_firma', 'fecha_de_inicio_del_contrato',
       'fecha_de_fin_del_contrato', 'fecha_inicio_liquidacion',
       'fecha_fin_liquidacion', 'localizaci_n', 'entidad_centralizada',
       'es_grupo', 'proceso_de_compra', 'modalidad_de_contratacion',
       'justificacion_modalidad_de', 'codigo_de_categoria_principal',
       'descripcion_del_proceso', 'objeto_del_contrato',
       'origen_de_los_recursos', 'destino_gasto', 'habilita_pago_adelantado',
       'obligaciones_postconsumo', 'reversion', 'valor_de_pago_adelantado',
       'valor_facturado', 'valor_amortizado', 'valor_pendiente_de',
       'valor_pendiente_de_ejecucion', 'dias_adicionados',
       'duraci_n_del_contrato', 'el_contrato_puede_ser_prorrogado',
       'urlproceso', 'ultima_actualizacion'],
      dtype='str')

In [4]:
total_nulls = df.isnull().sum()
(total_nulls / df.shape[0]*100).sort_values(ascending=False)

fecha_fin_liquidacion               88.474200
fecha_inicio_liquidacion            88.473612
ultima_actualizacion                37.239133
fecha_de_inicio_del_contrato         1.166594
valor_pendiente_de_ejecucion         0.049452
duraci_n_del_contrato                0.049452
urlproceso                           0.049452
valor_pendiente_de                   0.049452
dias_adicionados                     0.049452
el_contrato_puede_ser_prorrogado     0.049452
valor_amortizado                     0.049186
valor_facturado                      0.043036
valor_de_pago_adelantado             0.043036
obligaciones_postconsumo             0.038669
fecha_de_fin_del_contrato            0.000797
documento_proveedor                  0.000607
proveedor_adjudicado                 0.000475
objeto_del_contrato                  0.000095
departamento                         0.000000
tipodocproveedor                     0.000000
codigo_proveedor                     0.000000
valor_pagado                         0.000000
valor_pendiente_de_pago              0.000000
valor_del_contrato                   0.000000
espostconflicto                      0.000000
obligaci_n_ambiental                 0.000000
liquidaci_n                          0.000000
tipo_de_contrato                     0.000000
estado_contrato                      0.000000
id_contrato                          0.000000
rama                                 0.000000
sector                               0.000000
orden                                0.000000
nombre_entidad                       0.000000
nit_entidad                          0.000000
codigo_entidad                       0.000000
ciudad                               0.000000
descripcion_del_proceso              0.000000
codigo_de_categoria_principal        0.000000
proceso_de_compra                    0.000000
es_grupo                             0.000000
entidad_centralizada                 0.000000
localizaci_n                         0.000000
es_pyme                              0.000000
fecha_de_firma                       0.000000
justificacion_modalidad_de           0.000000
modalidad_de_contratacion            0.000000
reversion                            0.000000
origen_de_los_recursos               0.000000
destino_gasto                        0.000000
habilita_pago_adelantado             0.000000
dtype: float64

In [8]:
df['id_contrato'].duplicated().sum()

np.int64(971)

In [9]:
prueba = df.drop_duplicates()

In [10]:
prueba['id_contrato'].duplicated().sum()

np.int64(675)

In [13]:
prueba.loc[prueba['id_contrato'].duplicated(keep=False), ['id_contrato', 'fecha_de_firma','ultima_actualizacion','proveedor_adjudicado']].sort_values(by='id_contrato')

,id_contrato,fecha_de_firma,ultima_actualizacion,proveedor_adjudicado
5264597,CO1.PCCNTR.7809372,2026-07-07T00:00:00.000,NaN,MARIA ELVIRA GAMBOA BARRERA
5265521,CO1.PCCNTR.7809372,No,NaN,Funcionamiento
5264894,CO1.PCCNTR.8318411,2026-07-07T00:00:00.000,NaN,Construcciones Geadanke S.A.S
5266314,CO1.PCCNTR.8318411,No,NaN,Funcionamiento
5264796,CO1.PCCNTR.9324194,2026-07-07T00:00:00.000,NaN,eileen lizeth arias carrascal
...,...,...,...,...
5265057,CO1.PCCNTR.9629213,2026-07-07T00:00:00.000,NaN,Adriana del Pilar Carrillo Alvarez
5266292,CO1.PCCNTR.9629215,No,NaN,Inversión
5264884,CO1.PCCNTR.9629215,2026-07-07T00:00:00.000,NaN,CAMILA ROJAS ZAPE
5265504,CO1.PCCNTR.9629222,No,NaN,Inversión
5264641,CO1.PCCNTR.9629222,2026-07-07T00:00:00.000,NaN,Carlos Alberto Ramirez Martinez

In [6]:
df.head()

,departamento,ciudad,codigo_entidad,nit_entidad,nombre_entidad,orden,sector,rama,id_contrato,estado_contrato,...,valor_de_pago_adelantado,valor_facturado,valor_amortizado,valor_pendiente_de,valor_pendiente_de_ejecucion,dias_adicionados,duraci_n_del_contrato,el_contrato_puede_ser_prorrogado,urlproceso,ultima_actualizacion
0,Distrito Capital de Bogotá,Bogotá,700037070,900514813,COLOMBIA COMPRA EFICIENTE,Nacional,Planeación,Ejecutivo,CO1.PCCNTR.401,Cerrado,...,0,0,0,0,563760000,0,No definido,No,{'url': 'https://community.secop.gov.co/Public...,NaN
1,Distrito Capital de Bogotá,Bogotá,700037070,900514813,COLOMBIA COMPRA EFICIENTE,Nacional,Planeación,Ejecutivo,CO1.PCCNTR.701,Cerrado,...,0,0,0,0,732762,0,No definido,No,{'url': 'https://community.secop.gov.co/Public...,NaN
2,Distrito Capital de Bogotá,Bogotá,700090079,8001316486,FONDO UNICO DE TECNOLOGÍAS DE LA INFORMACIÓN Y...,Nacional,Tecnologías de la Información y las Comunicaci...,Ejecutivo,CO1.PCCNTR.1401,Cerrado,...,0,0,0,0,49000000,0,No definido,Si,{'url': 'https://community.secop.gov.co/Public...,NaN
3,Distrito Capital de Bogotá,Bogotá,700037070,900514813,COLOMBIA COMPRA EFICIENTE,Nacional,Planeación,Ejecutivo,CO1.PCCNTR.1601,Cerrado,...,0,0,0,0,7770000,0,No definido,No,{'url': 'https://community.secop.gov.co/Public...,NaN
4,Distrito Capital de Bogotá,Bogotá,700037070,900514813,COLOMBIA COMPRA EFICIENTE,Nacional,Planeación,Ejecutivo,CO1.PCCNTR.7803,Aprobado,...,0,0,0,0,119828000,0,No definido,Si,{'url': 'https://community.secop.gov.co/Public...,NaN

que tipo de dato es codigo_proveedor

In [7]:
mask = pd.to_numeric(df['codigo_proveedor'], errors='coerce').isnull()

In [8]:
mask.sum()

np.int64(0)

In [11]:
df['id_contrato'].duplicated().sum()

np.int64(0)

In [10]:
df.drop_duplicates(inplace=True)

In [12]:
df['entidad_centralizada'].value_counts()

entidad_centralizada
Centralizada       4170686
Descentralizada    1094144
Name: count, dtype: int64

In [13]:
df['es_grupo'].value_counts()

es_grupo
No    5230109
Si      34721
Name: count, dtype: int64

In [14]:
df['fecha_de_firma']

0          2024-01-01T00:00:00.000
1          2024-01-01T00:00:00.000
2          2024-01-01T00:00:00.000
3          2024-01-01T00:00:00.000
4          2024-01-01T00:00:00.000
                    ...
1898931    2025-12-31T00:00:00.000
1898932    2025-12-31T00:00:00.000
1898933    2025-12-31T00:00:00.000
1898934    2025-12-31T00:00:00.000
1898935    2025-12-31T00:00:00.000
Name: fecha_de_firma, Length: 1898936, dtype: str

In [15]:
proceso_per_contract = df.groupby('proceso_de_compra')['id_contrato'].count().sort_values(ascending=False)

In [16]:
proceso_per_contract.head(10)

proceso_de_compra
CO1.BDOS.1090482    647
CO1.BDOS.4130106    502
CO1.BDOS.5749845    491
CO1.BDOS.2794304    478
CO1.BDOS.5430521    395
CO1.BDOS.6192713    388
CO1.BDOS.4214324    385
CO1.BDOS.7214890    370
CO1.BDOS.3756536    368
CO1.BDOS.9816209    354
Name: id_contrato, dtype: int64

In [22]:
(proceso_per_contract.values > 1).sum() / len(proceso_per_contract) * 100

np.float64(1.7086852051920725)

Solo el 1.7% de los procesos de compra tienen mas de un contrato, por lo que no merece la pena crear una dimesion para el proceso de compra

In [23]:
df['modalidad_de_contratacion'].value_counts()

modalidad_de_contratacion
Contratación directa                                           4020744
Contratación régimen especial                                   698275
Mínima cuantía                                                  295179
Contratación Directa (con ofertas)                               68970
Selección Abreviada de Menor Cuantía                             54378
Selección abreviada subasta inversa                              45814
Contratación régimen especial (con ofertas)                      41610
Concurso de méritos abierto                                      14878
Licitación pública                                               13939
Licitación pública Obra Publica                                   8188
Licitación Pública Acuerdo Marco de Precios                       1180
Seleccion Abreviada Menor Cuantia Sin Manifestacion Interes       1178
Enajenación de bienes con sobre cerrado                            269
Enajenación de bienes con subasta                                  219
Concurso de méritos con precalificación                              9
Name: count, dtype: int64

In [53]:
df['origen_de_los_recursos'].value_counts()

origen_de_los_recursos
Distribuido         4233721
Recursos Propios    1031109
Name: count, dtype: int64

In [54]:
df['destino_gasto'].value_counts()

destino_gasto
Inversión         3262667
Funcionamiento    1980546
No aplica           12506
No Definido          9111
Name: count, dtype: int64

In [55]:
df['habilita_pago_adelantado'].value_counts()

habilita_pago_adelantado
No             4764232
No Definido     496906
Si                3692
Name: count, dtype: int64

In [56]:
df['obligaciones_postconsumo'].value_counts()

obligaciones_postconsumo
No    5263273
Si       1557
Name: count, dtype: int64

In [57]:
df['reversion'].value_counts()

reversion
No    5264184
Si        646
Name: count, dtype: int64

In [58]:
df['valor_de_pago_adelantado'].dtype

dtype('int64')

In [59]:
df['valor_facturado'].dtype

dtype('int64')

In [5]:
df['duraci_n_del_contrato'].dtype

In [67]:
df['el_contrato_puede_ser_prorrogado'].value_counts()

el_contrato_puede_ser_prorrogado
No    4339193
Si     925637
Name: count, dtype: int64

In [3]:
def remove_accents(text):
    if isinstance(text, str):
        return unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('utf-8')
    return text

def clean_text(series):
    return series.apply(remove_accents).str.upper().str.strip('*/+-.,;:[] ')

columns_to_clean = ['ciudad', 'departamento', 'nombre_entidad', 'sector', 'rama', 'orden',
                        'estado_contrato', 'tipo_de_contrato', 'tipodocproveedor', 'proveedor_adjudicado', 'modalidad_de_contratacion', 
                        'destino_gasto', 'origen_de_los_recursos']

for col in columns_to_clean:
    df[col] = clean_text(df[col])

table location

In [18]:
location = df[['ciudad','departamento']]
location.rename(columns={'ciudad':'city','departamento':'department'}, inplace=True)

In [19]:
location.drop_duplicates(inplace=True)

In [20]:
location.loc[location['city'].str.contains('BARRAN'), :]

                   city  department
2510       BARRANQUILLA   ATLANTICO
8293    BARRANCABERMEJA   SANTANDER
570842        BARRANCAS  LA GUAJIRA

In [21]:
len(location)
location['id_location'] = range(1,len(location)+1)

In [22]:
location.head()

         city department  id_location
0      TIMBIO      CAUCA            1
1  SAN MARTIN       META            2
2    ARBOLEDA     NARINO            3
3      RIVERA      HUILA            4
4   MANIZALES     CALDAS            5

table entity

In [45]:
df['entidad_centralizada'].value_counts()

entidad_centralizada
Centralizada       4170688
Descentralizada    1094437
Name: count, dtype: int64

In [7]:
entity = df[['codigo_entidad','nombre_entidad','nit_entidad','orden','sector','rama', 'ciudad','departamento','entidad_centralizada']]

entity.rename(columns={'ciudad': 'city', 'departamento': 'department','codigo_entidad':'id_entity',
                           'nombre_entidad':'name_entity','nit_entidad':'nit_entity','orden':'order_entity',
                           'rama':'branch_entity','sector':'sector_entity','entidad_centralizada':'centralized_entity'}, inplace=True)
    
entity.drop_duplicates(inplace=True)

In [10]:
entity['centralized_entity'] = entity['centralized_entity'].map({'Centralizada': True, 'Descentralizada': False})

In [11]:
entity.head()

,id_entity,name_entity,nit_entity,order_entity,sector_entity,branch_entity,city,department,centralized_entity
0,700037070,COLOMBIA COMPRA EFICIENTE,900514813,NACIONAL,PLANEACION,EJECUTIVO,BOGOTA,DISTRITO CAPITAL DE BOGOTA,True
2,700090079,FONDO UNICO DE TECNOLOGIAS DE LA INFORMACION Y...,8001316486,NACIONAL,TECNOLOGIAS DE LA INFORMACION Y LAS COMUNICACI...,EJECUTIVO,BOGOTA,DISTRITO CAPITAL DE BOGOTA,True
5,700209018,MINISTERIO DE AMBIENTE Y DESARROLLO SOSTENIBLE,830115395,NACIONAL,AMBIENTE Y DESARROLLO SOSTENIBLE,CORPORACION AUTONOMA,BOGOTA,DISTRITO CAPITAL DE BOGOTA,False
9,700183056,UNIDAD ADMINISTRATIVA ESPECIAL MIGRACION COLOMBIA,900477235,NACIONAL,RELACIONES EXTERIORES,EJECUTIVO,BOGOTA,DISTRITO CAPITAL DE BOGOTA,False
62,700358088,MINISTERIO DE COMERCIO INDUSTRIA Y TURISMO - M...,830115297,NACIONAL,INDUSTRIA,EJECUTIVO,BOGOTA,DISTRITO CAPITAL DE BOGOTA,True

In [8]:
entity['id_entity'].duplicated().sum()

np.int64(0)

In [4]:
provider = df[['codigo_proveedor','proveedor_adjudicado','documento_proveedor', 'es_pyme','tipodocproveedor']]

provider.rename(columns={'codigo_proveedor':'id_provider','proveedor_adjudicado':'name_provider',
                             'documento_proveedor':'provider_document','es_pyme':'is_pyme',
                             'tipodocproveedor':'type_of_provider', 'es_grupo':'is_group'}, inplace=True)

In [7]:
provider['type_of_provider'].value_counts()

type_of_provider
Cédula de Ciudadanía               1608514
NIT                                 281139
Otro                                  3462
No Definido                           2584
Cédula de Extranjería                 2295
Permiso por Protección Temporal        683
Tarjeta de Identidad                   112
Pasaporte                               73
Permiso especial de permanencia         59
Registro Civil                          15
Name: count, dtype: int64

In [18]:
provider['is_group'] = provider['is_group'].map({'Si': True, 'No': False})

In [13]:
provider.drop_duplicates(inplace=True)

In [14]:
provider['id_provider'].duplicated().sum()

np.int64(0)

In [20]:
provider['id_provider'].count()

np.int64(1203965)

In [28]:
df.loc[df['nit_entidad'].idxmax(), 'nit_entidad']

np.int64(9020055758)

In [ ]:
provider.sum()

In [9]:
#transform location data
location = df[['ciudad','departamento']]

location.rename(columns={'ciudad': 'city', 'departamento': 'department'}, inplace=True)

location.drop_duplicates(inplace=True)
location.reset_index(drop=True, inplace=True) 

location['id_location'] = range(1,len(location)+1)

In [10]:
pre_date = pd.concat([df['fecha_de_inicio_del_contrato'], df['fecha_de_fin_del_contrato'], df['fecha_de_firma'], df['fecha_inicio_liquidacion'], df['fecha_fin_liquidacion']])
    
date = pd.DataFrame(pre_date.drop_duplicates().dropna().reset_index(drop=True), columns=['date'])

#tranform date to datetime format
date['date'] = pd.to_datetime(date['date'], format='ISO8601', errors='coerce')
date.dropna(inplace=True)

#create new columns for year, month, day, quarter, week, day_of_week, day_name, month_name, is_weekend
date['year'] = date['date'].dt.year.astype('Int64')
date['month'] = date['date'].dt.month.astype('Int64')
date['day'] = date['date'].dt.day.astype('Int64')
date['quarter'] = date['date'].dt.quarter.astype('Int64')
date['week'] = date['date'].dt.isocalendar().week.astype('Int64')
date['day_of_week'] = date['date'].dt.dayofweek.astype('Int64')
date['day_name'] = date['date'].dt.day_name()
date['month_name'] = date['date'].dt.month_name()
date['is_weekend'] = date['day_of_week'].isin([5, 6])

#id_date
date['id_date'] = date['date'].dt.strftime('%Y%m%d').astype('Int64')

In [11]:
date['date'].max()

Timestamp('5025-12-20 00:00:00')

In [24]:
date.isnull().sum()

date           0
year           0
month          0
day            0
quarter        0
week           0
day_of_week    0
day_name       0
month_name     0
is_weekend     0
id_date        0
dtype: int64

In [ ]:
contract = df[['id_contrato','codigo_entidad','codigo_proveedor',
               
               'fecha_de_inicio_del_contrato',
               'fecha_de_fin_del_contrato','fecha_de_firma','fecha_inicio_liquidacion','fecha_fin_liquidacion', 'ultima_actualizacion',

               'estado_contrato', 'modalidad_de_contratacion', 'origen_de_los_recursos', 'destino_gasto','habilita_pago_adelantado',
               
               'valor_del_contrato','valor_pagado','valor_de_pago_adelantado','valor_pendiente_de_pago','valor_facturado','valor_amortizado',
               'valor_pendiente_de', 'valor_pendiente_de_ejecucion', 
               
               'dias_adicionados','el_contrato_puede_ser_prorrogado',

               'tipo_de_contrato','liquidaci_n','obligaci_n_ambiental','espostconflicto','obligaciones_postconsumo','reversion']]


contract.rename(columns={
    # IDs
    'id_contrato': 'id_contract',
    'codigo_entidad': 'id_entity',
    'codigo_proveedor': 'id_provider',

    # Dates
    'fecha_de_inicio_del_contrato': 'id_contract_start_date',
    'fecha_de_fin_del_contrato': 'id_contract_end_date',
    'fecha_de_firma': 'id_signing_date',
    'fecha_inicio_liquidacion': 'id_liquidation_start_date',
    'fecha_fin_liquidacion': 'id_liquidation_end_date',
    'ultima_actualizacion': 'id_last_update_date',

    # Contract information
    'estado_contrato': 'contract_state',
    'modalidad_de_contratacion': 'method_of_contracting',
    'origen_de_los_recursos': 'source_of_resources',
    'destino_gasto': 'destination_of_expense',
    'tipo_de_contrato': 'contract_type',

    # Monetary values
    'valor_del_contrato': 'contract_value',
    'valor_pagado': 'paid_value',
    'valor_de_pago_adelantado': 'advance_payment_value',
    'valor_pendiente_de_pago': 'pending_payment_value',
    'valor_facturado': 'invoiced_value',
    'valor_amortizado': 'amortized_value',
    'valor_pendiente_de': 'pending_amortization_value',
    'valor_pendiente_de_ejecucion': 'pending_execution_value',

    # Duration
    'dias_adicionados': 'additional_days',
    'el_contrato_puede_ser_prorrogado': 'contract_can_be_extended',

    # Booleans
    'liquidaci_n': 'liquidation',
    'obligaci_n_ambiental': 'environmental_obligation',
    'espostconflicto': 'is_post_conflict',
    'habilita_pago_adelantado': 'allows_advance_payment',
    'obligaciones_postconsumo': 'post_consumer_obligations',
    'reversion': 'reversion'
}, inplace=True)

contract.drop_duplicates(inplace=True)

    #transform contract dates to datetime format and then to integer format
contract['id_contract_start_date'] = pd.to_datetime(contract['id_contract_start_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')
contract['id_contract_end_date'] = pd.to_datetime(contract['id_contract_end_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')
contract['id_signing_date'] = pd.to_datetime(contract['id_signing_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')
contract['id_liquidation_start_date'] = pd.to_datetime(contract['id_liquidation_start_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')
contract['id_liquidation_end_date'] = pd.to_datetime(contract['id_liquidation_end_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')
contract['id_last_update_date'] = pd.to_datetime(contract['id_last_update_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')

contract['liquidation'] = contract['liquidation'].map({'Si': True, 'No': False})
contract['environmental_obligation'] = contract['environmental_obligation'].map({'Si': True, 'No': False})
contract['is_post_conflict'] = contract['is_post_conflict'].map({'Si': True, 'No': False})
contract['allows_advance_payment'] = contract['allows_advance_payment'].map({'Si': True, 'No': False})
contract['post_consumer_obligations'] = contract['post_consumer_obligations'].map({'Si': True, 'No': False})
contract['reversion'] = contract['reversion'].map({'Si': True, 'No': False})
contract['contract_can_be_extended'] = contract['contract_can_be_extended'].map({'Si': True, 'No': False})

In [40]:
contract['additional_days'].describe()

count    5.264830e+06
mean     1.030991e+01
std      1.150508e+03
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      7.305460e+05
Name: additional_days, dtype: float64

In [41]:
contract['additional_days'].sort_values(ascending=False).head(20)

5140252    730546
4762818    730546
4975152    730533
4976109    730533
4672616    730516
4727171    730491
4497172    730485
4684015    665108
5002180    664776
5041482    664757
5120922    664743
4514106    664742
2414073    664742
4810010    664741
1492839    365334
4579921     14276
981504       8399
4877473      7517
5059128      7334
545674       6759
Name: additional_days, dtype: int64

In [43]:
contract.loc[
    contract['additional_days'] >= 3650,
    [
        'id_contract',
        'id_contract_start_date',
        'id_contract_end_date',
        'additional_days'
    ]
].sort_values(by='additional_days', ascending=False).head(20)

,id_contract,id_contract_start_date,id_contract_end_date,additional_days
5140252,CO1.PCCNTR.9280585,20260130,20260530,730546
4762818,CO1.PCCNTR.8877883,20260115,20260731,730546
4976109,CO1.PCCNTR.9117064,20260127,20260626,730533
4975152,CO1.PCCNTR.9093689,20260126,20260610,730533
4672616,CO1.PCCNTR.8753328,20260102,20260802,730516
4727171,CO1.PCCNTR.8810636,20260119,20261218,730491
4497172,CO1.PCCNTR.8448805,20251014,20251213,730485
4684015,CO1.PCCNTR.8767279,20260107,20260706,665108
5002180,CO1.PCCNTR.9086287,20260127,20260511,664776
5041482,CO1.PCCNTR.9172751,20260211,20260610,664757
5120922,CO1.PCCNTR.9297047,20260202,20261001,664743
4514106,CO1.PCCNTR.8479030,20251022,20251205,664742
2414073,CO1.PCCNTR.5048181,20230609,20240606,664742
4810010,CO1.PCCNTR.8928898,20260205,20261231,664741
1492839,CO1.PCCNTR.3502925,20220208,30230107,365334
4579921,CO1.PCCNTR.8596968,20251114,20650131,14276
981504,CO1.PCCNTR.2629780,20210804,20490802,8399
4877473,CO1.PCCNTR.8990592,20260122,20260821,7517
5059128,CO1.PCCNTR.9196406,20260227,20461126,7334
545674,CO1.PCCNTR.1746811,20200826,20401231,6759

In [44]:
(contract['additional_days'] > 10000).sum()

np.int64(16)

In [18]:
contract[['contract_state',
    'method_of_contracting',
    'source_of_resources',
    'destination_of_expense',
    'contract_type']].head()

,contract_state,method_of_contracting,source_of_resources,destination_of_expense,contract_type
0,CERRADO,CONTRATACION DIRECTA (CON OFERTAS),DISTRIBUIDO,INVERSION,PRESTACION DE SERVICIOS
1,CERRADO,MINIMA CUANTIA,DISTRIBUIDO,FUNCIONAMIENTO,SUMINISTROS
2,CERRADO,MINIMA CUANTIA,DISTRIBUIDO,INVERSION,PRESTACION DE SERVICIOS
3,CERRADO,CONTRATACION DIRECTA (CON OFERTAS),DISTRIBUIDO,FUNCIONAMIENTO,PRESTACION DE SERVICIOS
4,APROBADO,CONTRATACION REGIMEN ESPECIAL,DISTRIBUIDO,FUNCIONAMIENTO,PRESTACION DE SERVICIOS

In [19]:
contract[['contract_value',
   'paid_value',
    'advance_payment_value',
    'pending_payment_value',
    'invoiced_value',
    'amortized_value',
    'pending_amortization_value',
    'pending_execution_value']]

,contract_value,paid_value,advance_payment_value,pending_payment_value,invoiced_value,amortized_value,pending_amortization_value,pending_execution_value
0,563760000,0,0,563760000,0,0,0,563760000
1,732762,0,0,732762,0,0,0,732762
2,49000000,0,0,49000000,0,0,0,49000000
3,7770000,0,0,7770000,0,0,0,7770000
4,119828000,0,0,119828000,0,0,0,119828000
...,...,...,...,...,...,...,...,...
5265120,28476144,0,0,28476144,0,0,0,28476144
5265121,7700000,0,0,7700000,0,0,0,7700000
5265122,1576246128,0,0,1576246128,0,0,0,1576246128
5265123,114406170,0,0,114406170,0,0,0,114406170
5265124,13368025,0,0,13368025,0,0,0,13368025

In [20]:
contract[['additional_days',
    'contract_duration_days',
    'contract_can_be_extended']]

         additional_days contract_duration_days  contract_can_be_extended
0                      0            No definido                     False
1                      0            No definido                     False
2                      0            No definido                      True
3                      0            No definido                     False
4                      0            No definido                      True
...                  ...                    ...                       ...
5265120                0              6 Mes(es)                     False
5265121                0              1 Mes(es)                     False
5265122                0             174 Dia(s)                     False
5265123                0             149 Dia(s)                     False
5265124                0              4 Mes(es)                      True

[5264830 rows x 3 columns]

In [21]:
contract[['liquidation',
    'environmental_obligation',
    'is_post_conflict',
    'allows_advance_payment',
    'post_consumer_obligations',
    'reversion']]

,liquidation,environmental_obligation,is_post_conflict,allows_advance_payment,post_consumer_obligations,reversion
0,False,False,False,NaN,False,False
1,False,False,False,NaN,False,False
2,False,False,False,NaN,False,False
3,False,False,False,NaN,False,False
4,False,False,False,NaN,False,False
...,...,...,...,...,...,...
5265120,False,False,False,False,False,False
5265121,False,False,False,False,False,False
5265122,True,False,False,False,False,False
5265123,True,False,False,False,False,False
5265124,False,False,False,False,False,False

In [23]:
contract['post_consumer_obligations'].value_counts()

post_consumer_obligations
False    5263273
True        1557
Name: count, dtype: int64

In [38]:
contract['method_of_contracting'].value_counts()

method_of_contracting
CONTRATACION DIRECTA                                           4020744
CONTRATACION REGIMEN ESPECIAL                                   698275
MINIMA CUANTIA                                                  295179
CONTRATACION DIRECTA (CON OFERTAS                                68970
SELECCION ABREVIADA DE MENOR CUANTIA                             54378
SELECCION ABREVIADA SUBASTA INVERSA                              45814
CONTRATACION REGIMEN ESPECIAL (CON OFERTAS                       41610
CONCURSO DE MERITOS ABIERTO                                      14878
LICITACION PUBLICA                                               13939
LICITACION PUBLICA OBRA PUBLICA                                   8188
LICITACION PUBLICA ACUERDO MARCO DE PRECIOS                       1180
SELECCION ABREVIADA MENOR CUANTIA SIN MANIFESTACION INTERES       1178
ENAJENACION DE BIENES CON SOBRE CERRADO                            269
ENAJENACION DE BIENES CON SUBASTA                                  219
CONCURSO DE MERITOS CON PRECALIFICACION                              9
Name: count, dtype: int64

In [6]:
contract.loc[(contract['id_contract_start_date'].isnull()) | (contract['id_contract_end_date'].isnull()) | (contract['id_signing_date'].isnull()) | (contract['id_liquidation_start_date'].isnull()) | (contract['id_liquidation_end_date'].isnull()), :]

,id_contract,id_entity,id_provider,id_contract_start_date,id_contract_end_date,id_signing_date,id_liquidation_start_date,id_liquidation_end_date,contract_state,contract_value,pending_payment_amount,paid_amount,contract_type,liquidation,environmental_obligation,is_post_conflict
0,CO1.PCCNTR.5707540,710500463,719294506,20240101,20240930,20240101,<NA>,<NA>,Modificado,24341985,24341985,0,Decreto 092 de 2017,False,False,False
1,CO1.PCCNTR.5707355,705985851,720225374,20240101,20240131,20240101,<NA>,<NA>,terminado,1730400,1730400,0,Prestación de servicios,False,False,False
2,CO1.PCCNTR.5707810,716359328,724132030,20240102,20240229,20240101,<NA>,<NA>,En ejecución,4400000,4400000,0,Prestación de servicios,False,False,False
5,CO1.PCCNTR.5707426,704561976,706212982,20240101,20240229,20240101,<NA>,<NA>,terminado,7600000,7600000,0,Decreto 092 de 2017,False,False,False
6,CO1.PCCNTR.5703037,704403419,720215144,20240101,20240331,20240101,<NA>,<NA>,En ejecución,4914000,4914000,0,Decreto 092 de 2017,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1898929,CO1.PCCNTR.8747181,704155118,707714598,20251231,20260731,20251231,<NA>,<NA>,Modificado,743158678,743158678,0,Otro,False,False,False
1898930,CO1.PCCNTR.8745868,700077019,703382077,20260505,20270204,20251231,<NA>,<NA>,Modificado,17856807658,17856807658,0,Otro,False,False,False
1898931,CO1.PCCNTR.8743449,725716054,731969598,20251231,20251231,20251231,<NA>,<NA>,En ejecución,11490000,11490000,0,Compraventa,False,False,False
1898933,CO1.PCCNTR.8734716,700964026,700648058,20260113,20260131,20251231,<NA>,<NA>,En ejecución,5688015,0,5688015,Compraventa,False,False,False
1898934,CO1.PCCNTR.8746765,700676059,716636923,20260105,20250904,20251231,<NA>,<NA>,En ejecución,44982000,17617950,27364050,Prestación de servicios,False,False,False

In [24]:
contract.loc[contract['contract_duration_days'] == '174 Dia(s)',['id_contract','contract_duration_days','id_contract_start_date','id_contract_end_date']]

,id_contract,contract_duration_days,id_contract_start_date,id_contract_end_date
470449,CO1.PCCNTR.1600813,174 Dia(s),20200608,20201009
475676,CO1.PCCNTR.1635819,174 Dia(s),20200624,20201214
476116,CO1.PCCNTR.1642920,174 Dia(s),20200623,20201216
476124,CO1.PCCNTR.1638692,174 Dia(s),20200623,20201216
476315,CO1.PCCNTR.1638964,174 Dia(s),20200623,20201216
...,...,...,...,...
5264912,CO1.PCCNTR.9628332,174 Dia(s),<NA>,20261230
5264958,CO1.PCCNTR.9624548,174 Dia(s),<NA>,20261229
5265003,CO1.PCCNTR.9628964,174 Dia(s),<NA>,20261230
5265010,CO1.PCCNTR.9626153,174 Dia(s),<NA>,20261230
5265122,CO1.PCCNTR.9624422,174 Dia(s),<NA>,20261231

In [35]:
contract['contract_duration_days'].unique()

<StringArray>
[    'No definido',          'Dia(s)',      '11 Mes(es)',       '7 Mes(es)',
       '6 Mes(es)',       '27 Dia(s)',       '65 Dia(s)',      '105 Dia(s)',
       '5 Mes(es)',       '3 Mes(es)',
 ...
     '2304 Dia(s)',     '2230 Dia(s)',     '2038 Dia(s)',     '3498 Dia(s)',
     '3492 Dia(s)',     '3483 Dia(s)',     '1653 Dia(s)',     '3476 Dia(s)',
     '1893 Dia(s)', '16583268 Dia(s)']
Length: 3118, dtype: str

In [30]:
d2['date'] - d1['date']

1510   NaT
1522   NaT
Name: date, dtype: timedelta64[us]

In [27]:
# fecha de inicio antes que fecha de firma
mask1 = contract['id_contract_start_date'] < contract['id_signing_date']

# fecha de fin antes que fecha de inicio
mask2 = contract['id_contract_end_date'] < contract['id_contract_start_date']

# fecha de liquidacion antes que fecha de fin
mask3 = contract['id_liquidation_start_date'] < contract['id_contract_end_date']

print(f"Inicio antes que firma: {mask1.sum()}")
print(f"Fin antes que inicio: {mask2.sum()}")
print(f"Liquidacion antes que fin: {mask3.sum()}")

Inicio antes que firma: 210076
Fin antes que inicio: 727
Liquidacion antes que fin: 106080

In [28]:
contract.loc[mask2,:]

,id_contract,id_entity,id_provider,id_contract_start_date,id_contract_end_date,id_signing_date,id_liquidation_start_date,id_liquidation_end_date,id_last_update_date,contract_state,...,pending_execution_value,additional_days,contract_duration_days,contract_can_be_extended,contract_type,liquidation,environmental_obligation,is_post_conflict,post_consumer_obligations,reversion
412097,CO1.PCCNTR.1428670,702271321,708925532,20260408,20200730,20200316,<NA>,<NA>,<NA>,APROBADO,...,11883200,0,Dia(s),False,PRESTACION DE SERVICIOS,False,False,False,NaN,False
499489,CO1.PCCNTR.1560044,702769076,707169249,20200717,20200630,20200717,<NA>,<NA>,<NA>,APROBADO,...,2592576,0,48 Dia(s),True,PRESTACION DE SERVICIOS,False,False,False,NaN,False
500197,CO1.PCCNTR.1697786,702769076,703116699,20200717,20200715,20200717,<NA>,<NA>,<NA>,APROBADO,...,1499000,0,30 Dia(s),True,PRESTACION DE SERVICIOS,False,False,False,NaN,False
593320,CO1.PCCNTR.1874181,704258359,702392077,20210901,20201231,20201016,<NA>,<NA>,<NA>,APROBADO,...,100000000,0,4 Mes(es),False,PRESTACION DE SERVICIOS,False,False,False,NaN,False
655246,CO1.PCCNTR.2061836,702318460,707966289,20210930,20201231,20201216,<NA>,<NA>,<NA>,APROBADO,...,2249000,0,15 Dia(s),False,PRESTACION DE SERVICIOS,False,False,False,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4927754,CO1.PCCNTR.8986126,705402857,727902371,20260122,20260119,20260122,20260830,20260830,<NA>,EN EJECUCION,...,22470000,0,180 Dia(s),True,PRESTACION DE SERVICIOS,True,False,False,NaN,False
4946018,CO1.PCCNTR.9031217,718458664,733733034,20260123,20260121,20260123,<NA>,<NA>,<NA>,EN EJECUCION,...,6978400,0,6 Mes(es),True,PRESTACION DE SERVICIOS,False,False,False,NaN,False
4952620,CO1.PCCNTR.9085710,719523268,734482227,20260123,20251226,20260123,20261230,20281230,<NA>,EN EJECUCION,...,4352800,0,2 Dia(s),False,SUMINISTROS,True,False,False,NaN,False
4954519,CO1.PCCNTR.8941651,708964812,704345115,20260123,20260116,20260123,20260112,20270416,<NA>,EN EJECUCION,...,17317300,0,173 Dia(s),True,PRESTACION DE SERVICIOS,True,False,False,NaN,False
4962269,CO1.PCCNTR.9094963,713901304,735099673,20260123,20250130,20260123,20260131,20260430,<NA>,EN EJECUCION,...,2200000,0,1 Mes(es),False,PRESTACION DE SERVICIOS,True,False,False,NaN,False