In [1]:
import pandas as pd
import unicodedata

In [2]:
df = pd.read_csv("../data/raw/secop2-2426.csv")

tamaño del csv

In [9]:
df.shape

(1898936, 27)

In [10]:
df.columns

Index(['departamento', 'ciudad', 'codigo_entidad', 'nit_entidad',
       'nombre_entidad', 'orden', 'sector', 'rama', 'id_contrato',
       'estado_contrato', 'tipo_de_contrato', 'liquidaci_n',
       'obligaci_n_ambiental', 'espostconflicto', 'valor_del_contrato',
       'valor_pendiente_de_pago', 'valor_pagado', 'codigo_proveedor',
       'tipodocproveedor', 'documento_proveedor', 'proveedor_adjudicado',
       'es_pyme', 'fecha_de_firma', 'fecha_de_inicio_del_contrato',
       'fecha_de_fin_del_contrato', 'fecha_inicio_liquidacion',
       'fecha_fin_liquidacion'],
      dtype='str')

In [24]:
total_nulls = df.isnull().sum()
(total_nulls / df.shape[0]*100).sort_values(ascending=False)

fecha_fin_liquidacion           87.558980
fecha_inicio_liquidacion        87.557506
fecha_de_inicio_del_contrato     0.753949
documento_proveedor              0.000685
proveedor_adjudicado             0.000685
fecha_de_fin_del_contrato        0.000053
nombre_entidad                   0.000000
nit_entidad                      0.000000
departamento                     0.000000
ciudad                           0.000000
codigo_entidad                   0.000000
tipo_de_contrato                 0.000000
estado_contrato                  0.000000
id_contrato                      0.000000
rama                             0.000000
sector                           0.000000
orden                            0.000000
liquidaci_n                      0.000000
obligaci_n_ambiental             0.000000
tipodocproveedor                 0.000000
codigo_proveedor                 0.000000
valor_pagado                     0.000000
valor_pendiente_de_pago          0.000000
valor_del_contrato               0.000000
espostconflicto                  0.000000
fecha_de_firma                   0.000000
es_pyme                          0.000000
dtype: float64

In [12]:
df.head()

,departamento,ciudad,codigo_entidad,nit_entidad,nombre_entidad,orden,sector,rama,id_contrato,estado_contrato,...,codigo_proveedor,tipodocproveedor,documento_proveedor,proveedor_adjudicado,es_pyme,fecha_de_firma,fecha_de_inicio_del_contrato,fecha_de_fin_del_contrato,fecha_inicio_liquidacion,fecha_fin_liquidacion
0,Cauca,Timbío,710500463,817000999,HOSPITAL TIMBIO ESE,Territorial,Salud y Protección Social,Corporación Autónoma,CO1.PCCNTR.5707540,Modificado,...,719294506,Cédula de Ciudadanía,34658915,SANDRA LILIANA CLAVIJO MOLINA,No,2024-01-01T00:00:00.000,2024-01-01T00:00:00.000,2024-09-30T00:00:00.000,NaN,NaN
1,Meta,San Martín,705985851,892000458,EMPRESA SOCIAL DEL ESTADO HOSPITAL LOCAL DE SA...,Nacional,Salud y Protección Social,Ejecutivo,CO1.PCCNTR.5707355,terminado,...,720225374,Cédula de Ciudadanía,1073719989,LISBETH DAYELLI ROZO SALDAÑA,No,2024-01-01T00:00:00.000,2024-01-01T00:00:00.000,2024-01-31T00:00:00.000,NaN,NaN
2,Nariño,Arboleda,716359328,900135676,Ese Centro de Salud San Miguel,Territorial,Salud y Protección Social,Corporación Autónoma,CO1.PCCNTR.5707810,En ejecución,...,724132030,Cédula de Ciudadanía,1085329201,LUISA MARIA BENAVIDES VERGARA,No,2024-01-01T00:00:00.000,2024-01-02T00:00:00.000,2024-02-29T00:00:00.000,NaN,NaN
3,Huila,Rivera,714657632,813002933,EMPRESA SOCIAL DEL ESTADO HOSPITAL DIVINO NIÑO,Territorial,Salud y Protección Social,Corporación Autónoma,CO1.PCCNTR.5707593,Modificado,...,724422027,Cédula de Ciudadanía,1053818566,MARIA CAMILA VARON CALDERON,No,2024-01-01T00:00:00.000,2024-01-01T00:00:00.000,2024-03-31T00:00:00.000,2024-04-01T00:00:00.000,2024-06-30T00:00:00.000
4,Caldas,Manizales,704527647,890801099,HOSPITAL DEPARTAMENTAL UNIVERSITARIO SANTA SOF...,Territorial,Salud y Protección Social,Ejecutivo,CO1.PCCNTR.5705140,Cerrado,...,720324235,Cédula de Ciudadanía,16073507,KEVIN FERNANDO MONTOYA QUINTERO,No,2024-01-01T00:00:00.000,2024-01-01T00:00:00.000,2024-12-31T00:00:00.000,2025-01-01T00:00:00.000,2025-03-20T00:00:00.000

que tipo de dato es codigo_proveedor

In [13]:
mask = pd.to_numeric(df['codigo_proveedor'], errors='coerce').isnull()

In [14]:
mask.sum()

np.int64(0)

In [15]:
df['id_contrato'].duplicated().sum()

np.int64(155)

In [16]:
df.drop_duplicates(inplace=True)

In [17]:
def remove_accents(text):
    if isinstance(text, str):
        return unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('utf-8')
    return text

def clean_text(series):
    return series.apply(remove_accents).str.upper().str.strip('*/+-.,;:()[] ')

df['ciudad'] = clean_text(df['ciudad'])
df['departamento'] = clean_text(df['departamento'])

df['nombre_entidad'] = clean_text(df['nombre_entidad'])
df['sector'] = clean_text(df['sector'])
df['rama'] = clean_text(df['rama'])
df['orden'] = clean_text(df['orden'])

df['estado_contrato'] = clean_text(df['estado_contrato'])
df['tipo_de_contrato'] = clean_text(df['tipo_de_contrato'])

df['tipodocproveedor'] = clean_text(df['tipodocproveedor'])
df['proveedor_adjudicado'] = clean_text(df['proveedor_adjudicado'])

table location

In [18]:
location = df[['ciudad','departamento']]
location.rename(columns={'ciudad':'city','departamento':'department'}, inplace=True)

In [19]:
location.drop_duplicates(inplace=True)

In [20]:
location.loc[location['city'].str.contains('BARRAN'), :]

                   city  department
2510       BARRANQUILLA   ATLANTICO
8293    BARRANCABERMEJA   SANTANDER
570842        BARRANCAS  LA GUAJIRA

In [21]:
len(location)
location['id_location'] = range(1,len(location)+1)

In [22]:
location.head()

         city department  id_location
0      TIMBIO      CAUCA            1
1  SAN MARTIN       META            2
2    ARBOLEDA     NARINO            3
3      RIVERA      HUILA            4
4   MANIZALES     CALDAS            5

table entity

In [23]:
entity = df[['codigo_entidad','nombre_entidad','nit_entidad','orden','sector','rama', 'ciudad','departamento']]

entity.rename(columns={'ciudad': 'city', 'departamento': 'department','codigo_entidad':'id_entity',
                           'nombre_entidad':'name_entity','nit_entidad':'nit_entity','orden':'order_entity',
                           'rama':'branch_entity','sector':'sector_entity'}, inplace=True)
    
entity.drop_duplicates(inplace=True)

In [24]:
entity['id_entity'].duplicated().sum()

np.int64(0)

In [25]:
provider = df[['codigo_proveedor','proveedor_adjudicado','documento_proveedor', 'es_pyme','tipodocproveedor']]

provider.rename(columns={'codigo_proveedor':'id_provider','proveedor_adjudicado':'name_provider',
                             'documento_proveedor':'provider_document','es_pyme':'is_pyme',
                             'tipodocproveedor':'type_of_provider'}, inplace=True)

In [26]:
provider.drop_duplicates(inplace=True)

In [27]:
provider['id_provider'].dtype

dtype('int64')

In [28]:
df.loc[df['nit_entidad'].idxmax(), 'nit_entidad']

np.int64(9020055758)

In [ ]:
provider.sum()

In [7]:
def remove_accents(text):
    if isinstance(text, str):
        return unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('utf-8')
    return text

def clean_text(series):
    return series.apply(remove_accents).str.upper().str.strip('*/+-.,;:()[] ')

In [8]:
# Clean text columns
df['ciudad'] = clean_text(df['ciudad'])
df['departamento'] = clean_text(df['departamento'])

df['nombre_entidad'] = clean_text(df['nombre_entidad'])
df['sector'] = clean_text(df['sector'])
df['rama'] = clean_text(df['rama'])
df['orden'] = clean_text(df['orden'])

df['estado_contrato'] = clean_text(df['estado_contrato'])
df['tipo_de_contrato'] = clean_text(df['tipo_de_contrato'])

df['tipodocproveedor'] = clean_text(df['tipodocproveedor'])
df['proveedor_adjudicado'] = clean_text(df['proveedor_adjudicado'])

In [9]:
#transform location data
location = df[['ciudad','departamento']]

location.rename(columns={'ciudad': 'city', 'departamento': 'department'}, inplace=True)

location.drop_duplicates(inplace=True)
location.reset_index(drop=True, inplace=True) 

location['id_location'] = range(1,len(location)+1)

In [10]:
entity = df[['codigo_entidad','nombre_entidad','nit_entidad','orden','sector','rama', 'ciudad','departamento']]

entity.rename(columns={'ciudad': 'city', 'departamento': 'department','codigo_entidad':'id_entity',
                        'nombre_entidad':'name_entity','nit_entidad':'nit_entity','orden':'order_entity',
                        'rama':'branch_entity','sector':'sector_entity'}, inplace=True)


entity.drop_duplicates(inplace=True)
entity = entity.merge(location, on=['city','department'], how='left')

entity.drop(columns=['city','department'], inplace=True)

#transform provider data
provider = df[['codigo_proveedor','proveedor_adjudicado','documento_proveedor', 'es_pyme','tipodocproveedor']]

provider.rename(columns={'codigo_proveedor':'id_provider','proveedor_adjudicado':'name_provider',
                            'documento_proveedor':'provider_document','es_pyme':'is_pyme',
                            'tipodocproveedor':'type_of_provider'}, inplace=True)

provider.drop_duplicates(inplace=True)

provider['is_pyme'] = provider['is_pyme'].map({'Si': True, 'No': False})

In [ ]:
pre_date = pd.concat([df['fecha_de_inicio_del_contrato'], df['fecha_de_fin_del_contrato'], df['fecha_de_firma'], df['fecha_inicio_liquidacion'], df['fecha_fin_liquidacion']])
    
date = pd.DataFrame(pre_date.drop_duplicates().dropna().reset_index(drop=True), columns=['date'])

#tranform date to datetime format
date['date'] = pd.to_datetime(date['date'], format='ISO8601', errors='coerce')
date.dropna(inplace=True)
date['date'] = date['date'].where(date['date'].dt.year >= 1900 & date['date'].dt.year <= 2050, pd.NaT)

#create new columns for year, month, day, quarter, week, day_of_week, day_name, month_name, is_weekend
date['year'] = date['date'].dt.year.astype('Int64')
date['month'] = date['date'].dt.month.astype('Int64')
date['day'] = date['date'].dt.day.astype('Int64')
date['quarter'] = date['date'].dt.quarter.astype('Int64')
date['week'] = date['date'].dt.isocalendar().week.astype('Int64')
date['day_of_week'] = date['date'].dt.dayofweek.astype('Int64')
date['day_name'] = date['date'].dt.day_name()
date['month_name'] = date['date'].dt.month_name()
date['is_weekend'] = date['day_of_week'].isin([5, 6])

#id_date
date['id_date'] = date['date'].dt.strftime('%Y%m%d').astype('Int64')

In [12]:
#transform provider data
provider = df[['codigo_proveedor','proveedor_adjudicado','documento_proveedor', 'es_pyme','tipodocproveedor']]

provider.rename(columns={'codigo_proveedor':'id_provider','proveedor_adjudicado':'name_provider',
                            'documento_proveedor':'provider_document','es_pyme':'is_pyme',
                            'tipodocproveedor':'type_of_provider'}, inplace=True)

provider.drop_duplicates(inplace=True)

provider['is_pyme'] = provider['is_pyme'].map({'Si': True, 'No': False})

In [13]:
contract = df[['id_contrato','codigo_entidad','codigo_proveedor','fecha_de_inicio_del_contrato',
               'fecha_de_fin_del_contrato','fecha_de_firma','fecha_inicio_liquidacion','fecha_fin_liquidacion',
               'estado_contrato','valor_del_contrato','valor_pendiente_de_pago','valor_pagado','tipo_de_contrato',
               'liquidaci_n','obligaci_n_ambiental','espostconflicto']]
    
contract.rename(columns={'id_contrato':'id_contract','codigo_entidad':'id_entity','codigo_proveedor':'id_provider',
                            'fecha_de_inicio_del_contrato':'id_contract_start_date',
                        'fecha_de_fin_del_contrato':'id_contract_end_date','fecha_de_firma':'id_signing_date',
                        'fecha_inicio_liquidacion':'id_liquidation_start_date','fecha_fin_liquidacion':'id_liquidation_end_date',
                        'estado_contrato':'contract_state','valor_del_contrato':'contract_value',
                        'valor_pendiente_de_pago':'pending_payment_amount','valor_pagado':'paid_amount',
                        'tipo_de_contrato':'contract_type','liquidaci_n':'liquidation','obligaci_n_ambiental':'environmental_obligation',
                        'espostconflicto':'is_post_conflict'}, inplace=True)

contract.drop_duplicates(subset=['id_contract'], inplace=True)

    #transform contract dates to datetime format and then to integer format
contract['id_contract_start_date'] = pd.to_datetime(contract['id_contract_start_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')
contract['id_contract_end_date'] = pd.to_datetime(contract['id_contract_end_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')
contract['id_signing_date'] = pd.to_datetime(contract['id_signing_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')
contract['id_liquidation_start_date'] = pd.to_datetime(contract['id_liquidation_start_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')
contract['id_liquidation_end_date'] = pd.to_datetime(contract['id_liquidation_end_date'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')


contract['liquidation'] = contract['liquidation'].map({'Si': True, 'No': False})
contract['environmental_obligation'] = contract['environmental_obligation'].map({'Si': True, 'No': False})
contract['is_post_conflict'] = contract['is_post_conflict'].map({'Si': True, 'No': False})

In [26]:
contract.loc[(contract['id_contract_start_date'] > 30000000) | (contract['id_contract_end_date'] > 30000000) | (contract['id_signing_date'] > 30000000) | (contract['id_liquidation_start_date'] > 30000000) | (contract['id_liquidation_end_date'] > 30000000), :]

,id_contract,id_entity,id_provider,id_contract_start_date,id_contract_end_date,id_signing_date,id_liquidation_start_date,id_liquidation_end_date,contract_state,contract_value,pending_payment_amount,paid_amount,contract_type,liquidation,environmental_obligation,is_post_conflict
487451,CO1.PCCNTR.6493968,701231045,700141021,20240704,20271231,20240704,20280101,30280630,MODIFICADO,5117177258,4715423069,401754189,PRESTACION DE SERVICIOS,True,False,False
1624557,CO1.PCCNTR.8265594,702266396,700341068,20250904,50251220,20250904,20251220,20251220,EN EJECUCION,9688233,9688233,0,SEGUROS,True,False,False

In [17]:
# fecha de inicio antes que fecha de firma
mask1 = contract['id_contract_start_date'] < contract['id_signing_date']

# fecha de fin antes que fecha de inicio
mask2 = contract['id_contract_end_date'] < contract['id_contract_start_date']

# fecha de liquidacion antes que fecha de fin
mask3 = contract['id_liquidation_start_date'] < contract['id_contract_end_date']

print(f"Inicio antes que firma: {mask1.sum()}")
print(f"Fin antes que inicio: {mask2.sum()}")
print(f"Liquidacion antes que fin: {mask3.sum()}")

Inicio antes que firma: 385
Fin antes que inicio: 533
Liquidacion antes que fin: 44517

In [25]:
contract.loc[mask2,:]

,id_contract,id_entity,id_provider,id_contract_start_date,id_contract_end_date,id_signing_date,id_liquidation_start_date,id_liquidation_end_date,contract_state,contract_value,pending_payment_amount,paid_amount,contract_type,liquidation,environmental_obligation,is_post_conflict
165686,CO1.PCCNTR.5949483,703015735,720896141,20250215,20240430,20240215,<NA>,<NA>,APROBADO,229675413,229675413,0,DECRETO 092 DE 2017,False,False,False
347805,CO1.PCCNTR.6248107,718905318,703174540,20240425,20240424,20240425,20240815,20241121,APROBADO,300000000,300000000,0,SUMINISTROS,True,False,False
374327,CO1.PCCNTR.6233828,703905919,726272461,20250419,20240731,20240507,<NA>,<NA>,APROBADO,22500000,22500000,0,PRESTACION DE SERVICIOS,False,False,False
472003,CO1.PCCNTR.6466145,704883511,700306053,20240627,20240526,20240627,<NA>,<NA>,APROBADO,114442710,114442710,0,SEGUROS,False,False,False
635195,CO1.PCCNTR.6380459,704929405,718983158,20240909,20240731,20240909,<NA>,<NA>,APROBADO,4950000,4950000,0,PRESTACION DE SERVICIOS,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1897859,CO1.PCCNTR.8748850,704150309,725764070,20251231,20250730,20251231,<NA>,<NA>,EN EJECUCION,30762773,30762773,0,PRESTACION DE SERVICIOS,False,False,False
1898140,CO1.PCCNTR.8747436,700676059,724671524,20260108,20251230,20251231,<NA>,<NA>,EN EJECUCION,88751250,51964500,36786750,PRESTACION DE SERVICIOS,False,False,False
1898278,CO1.PCCNTR.8745318,703041459,708551015,20251231,20250731,20251231,20260801,20261101,EN EJECUCION,21812750,6204000,15608750,PRESTACION DE SERVICIOS,True,False,False
1898614,CO1.PCCNTR.8750173,702259441,712875418,20260103,20251226,20251231,<NA>,<NA>,EN EJECUCION,2083333,0,2083333,PRESTACION DE SERVICIOS,False,False,False
1898934,CO1.PCCNTR.8746765,700676059,716636923,20260105,20250904,20251231,<NA>,<NA>,EN EJECUCION,44982000,17617950,27364050,PRESTACION DE SERVICIOS,False,False,False