In [2]:
import requests
import pandas as pd

In [4]:
api_secop2 = 'https://www.datos.gov.co/resource/jbjy-vk9h.json'
all_data =[]
offset = 0
limit=1000

while True:
    response = requests.get(api_secop2, params={'$where': 'fecha_de_inicio_del_contrato >= "2024-01-01" AND fecha_de_inicio_del_contrato < "2026-01-01"','$limit': limit, '$offset': offset})
    if response.status_code == 200:
        data = response.json()
        if not data:
            break
        all_data.extend(data)
        offset += limit
    else:
        print(f"Error: {response.status_code}")
        break


df = pd.DataFrame(all_data)

Error: 503

In [7]:
df.head()

,nombre_entidad,nit_entidad,departamento,ciudad,localizaci_n,orden,sector,rama,entidad_centralizada,proceso_de_compra,...,tipo_de_documento_supervisor,n_mero_de_documento_supervisor,nombre_ordenador_de_pago,tipo_de_documento_ordenador_de_pago,n_mero_de_documento_ordenador_de_pago,documentos_tipo,descripcion_documentos_tipo,fecha_inicio_liquidacion,fecha_fin_liquidacion,fecha_de_notificaci_n_de_prorrogaci_n
0,HOSPITAL SAN JUAN DE DIOS ESE RIONEGRO,890907254,Antioquia,Rionegro,"Colombia, Antioquia, Rionegro",Territorial,Salud y Protección Social,Ejecutivo,Centralizada,CO1.BDOS.5327466,...,Cédula de Ciudadanía,39438012,No definido,No definido,No definido,No,No definido,NaN,NaN,NaN
1,INSTITUTO COLOMBIANO DE CREDITO EDUCATIVO Y ES...,899999035,Distrito Capital de Bogotá,Bogotá,"Colombia, Bogotá, Bogotá",Nacional,Educación Nacional,Ejecutivo,Centralizada,CO1.BDOS.5172483,...,Cédula de Ciudadanía,79434805,No definido,No definido,No definido,No,No definido,NaN,NaN,NaN
2,EMPRESA SOCIAL DEL ESTADO HOSPITAL LOCAL DE SA...,892000458,Meta,San Martín,"Colombia, Meta , San Martín",Nacional,Salud y Protección Social,Ejecutivo,Centralizada,CO1.BDOS.5360886,...,No definido,No definido,No definido,No definido,No definido,No,No definido,NaN,NaN,NaN
3,ARMADA NACIONAL - BASE NAVAL ARC SAN ANDRES,800141656,"San Andrés, Providencia y Santa Catalina",No Definido,"Colombia, San Andrés, Providencia y Santa Cat...",Nacional,defensa,Ejecutivo,Centralizada,CO1.BDOS.5330332,...,No definido,No definido,No definido,No definido,No definido,No,No definido,2024-12-31T00:00:00.000,2025-05-31T00:00:00.000,NaN
4,EMPRESA SOCIAL DEL ESTADO HOSPITAL DIVINO NIÑO,813002933,Huila,Rivera,"Colombia, Huila , Rivera",Territorial,Salud y Protección Social,Corporación Autónoma,Descentralizada,CO1.BDOS.5362023,...,Cédula de Ciudadanía,1081152775,No definido,No definido,No definido,No,No definido,2024-04-01T00:00:00.000,2024-06-30T00:00:00.000,NaN

In [15]:
df.columns

Index(['nombre_entidad', 'nit_entidad', 'departamento', 'ciudad',
       'localizaci_n', 'orden', 'sector', 'rama', 'entidad_centralizada',
       'proceso_de_compra', 'id_contrato', 'referencia_del_contrato',
       'estado_contrato', 'codigo_de_categoria_principal',
       'descripcion_del_proceso', 'tipo_de_contrato',
       'modalidad_de_contratacion', 'justificacion_modalidad_de',
       'fecha_de_firma', 'fecha_de_inicio_del_contrato',
       'fecha_de_fin_del_contrato', 'condiciones_de_entrega',
       'tipodocproveedor', 'documento_proveedor', 'proveedor_adjudicado',
       'es_grupo', 'es_pyme', 'habilita_pago_adelantado', 'liquidaci_n',
       'obligaci_n_ambiental', 'obligaciones_postconsumo', 'reversion',
       'origen_de_los_recursos', 'destino_gasto', 'valor_del_contrato',
       'valor_de_pago_adelantado', 'valor_facturado',
       'valor_pendiente_de_pago', 'valor_pagado', 'valor_amortizado',
       'valor_pendiente_de', 'valor_pendiente_de_ejecucion', 'saldo_cdp',
       'saldo_vigencia', 'espostconflicto', 'dias_adicionados',
       'puntos_del_acuerdo', 'pilares_del_acuerdo', 'urlproceso',
       'nombre_representante_legal', 'nacionalidad_representante_legal',
       'domicilio_representante_legal',
       'tipo_de_identificaci_n_representante_legal',
       'identificaci_n_representante_legal', 'g_nero_representante_legal',
       'presupuesto_general_de_la_nacion_pgn',
       'sistema_general_de_participaciones', 'sistema_general_de_regal_as',
       'recursos_propios_alcald_as_gobernaciones_y_resguardos_ind_genas_',
       'recursos_de_credito', 'recursos_propios', 'codigo_entidad',
       'codigo_proveedor', 'objeto_del_contrato', 'duraci_n_del_contrato',
       'nombre_del_banco', 'tipo_de_cuenta', 'n_mero_de_cuenta',
       'el_contrato_puede_ser_prorrogado', 'nombre_ordenador_del_gasto',
       'tipo_de_documento_ordenador_del_gasto',
       'n_mero_de_documento_ordenador_del_gasto', 'nombre_supervisor',
       'tipo_de_documento_supervisor', 'n_mero_de_documento_supervisor',
       'nombre_ordenador_de_pago', 'tipo_de_documento_ordenador_de_pago',
       'n_mero_de_documento_ordenador_de_pago', 'documentos_tipo',
       'descripcion_documentos_tipo', 'ultima_actualizacion',
       'fecha_de_notificaci_n_de_prorrogaci_n', 'fecha_inicio_liquidacion',
       'fecha_fin_liquidacion'],
      dtype='object')

In [16]:
df.loc[~df['localizaci_n'].str.startswith('C'), 'localizaci_n']

Series([], Name: localizaci_n, dtype: object)

In [214]:
df['es_pyme'].unique()

array(['No', 'Si'], dtype=object)

In [ ]:
total_null = df.isnull().sum()
total_row = df.shape[0]

nombre_entidad                                0
nit_entidad                                   0
departamento                                  0
ciudad                                        0
localizaci_n                                  0
                                          ...
documentos_tipo                               0
descripcion_documentos_tipo                   0
fecha_inicio_liquidacion                 424354
fecha_fin_liquidacion                    424359
fecha_de_notificaci_n_de_prorrogaci_n    430194
Length: 84, dtype: int64

In [219]:
total_null_percentage = (total_null / total_row) * 100

In [221]:
total_null_percentage.loc[total_null_percentage >0]

fecha_de_firma                            0.000421
ultima_actualizacion                     27.673684
n_mero_de_cuenta                          0.001684
fecha_inicio_liquidacion                 89.337684
fecha_fin_liquidacion                    89.338737
fecha_de_notificaci_n_de_prorrogaci_n    90.567158
dtype: float64

In [ ]:
df.loc[df['fecha_de_firma'] < 0, ['valor_del_contrato', 'fecha_de_inicio_del_contrato', 'fecha_de_fin_del_contrato', 'fecha_de_firma']]

Empty DataFrame
Columns: [valor_del_contrato, fecha_de_inicio_del_contrato, fecha_de_fin_del_contrato, fecha_de_firma]
Index: []

In [47]:
df['estado_contrato'].value_counts()

estado_contrato
En ejecución    64634
terminado       63403
Modificado      58298
Cerrado         43251
Suspendido       1265
cedido            276
Aprobado           47
Cancelado           4
Name: count, dtype: int64

#Table Localitation

In [11]:
localitation = df[['ciudad','departamento']]

In [15]:
localitation.value_counts()

ciudad         departamento
Abejorral      Antioquia       1
Quibdó         Chocó           1
Puerres        Nariño          1
Puerto Asís    Putumayo        1
Puerto Berrío  Antioquia       1
                              ..
Gambita        Santander       1
Gameza         Boyacá          1
Garagoa        Boyacá          1
Garzón         Huila           1
Zipaquirá      Cundinamarca    1
Name: count, Length: 654, dtype: int64

In [14]:
localitation.drop_duplicates(inplace=True)

C:\Users\bryan\AppData\Local\Temp\ipykernel_11148\2899386800.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  localitation.drop_duplicates(inplace=True)

In [23]:
localitation.reset_index(drop=True, inplace=True)

In [24]:
localitation['id_localitation'] = range(1,len(localitation)+1)

C:\Users\bryan\AppData\Local\Temp\ipykernel_11148\235054886.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  localitation['id_localitation'] = range(1,len(localitation)+1)

In [25]:
localitation.head()

        ciudad                              departamento  id_localitation
0     Rionegro                                 Antioquia                1
1       Bogotá                Distrito Capital de Bogotá                2
2   San Martín                                      Meta                3
3  No Definido  San Andrés, Providencia y Santa Catalina                4
4       Rivera                                     Huila                5

In [213]:
localitation.loc[localitation['departamento'] == 'Distrito Capital de Bogotá', ['departamento', 'ciudad']]

                   departamento            ciudad
1    Distrito Capital de Bogotá            Bogotá
46   Distrito Capital de Bogotá       No Definido
190  Distrito Capital de Bogotá  Distrito Capital

#Table entity

In [28]:
entity = df[['codigo_entidad','nombre_entidad','nit_entidad','orden','sector','rama', 'ciudad','departamento']]

In [31]:
len(entity)

475000

In [32]:
entity.drop_duplicates(inplace=True)

C:\Users\bryan\AppData\Local\Temp\ipykernel_11148\3585693747.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  entity.drop_duplicates(inplace=True)

In [34]:
entity = entity.merge(localitation, on=['ciudad','departamento'], how='left')

In [37]:
entity.drop(columns=['ciudad','departamento'], inplace=True)

In [196]:
entity.head()

,codigo_entidad,nombre_entidad,nit_entidad,orden,sector,rama,id_localitation
0,701728222,HOSPITAL SAN JUAN DE DIOS ESE RIONEGRO,890907254,Territorial,Salud y Protección Social,Ejecutivo,1
1,702350083,INSTITUTO COLOMBIANO DE CREDITO EDUCATIVO Y ES...,899999035,Nacional,Educación Nacional,Ejecutivo,2
2,705985851,EMPRESA SOCIAL DEL ESTADO HOSPITAL LOCAL DE SA...,892000458,Nacional,Salud y Protección Social,Ejecutivo,3
3,701192130,ARMADA NACIONAL - BASE NAVAL ARC SAN ANDRES,800141656,Nacional,defensa,Ejecutivo,4
4,714657632,EMPRESA SOCIAL DEL ESTADO HOSPITAL DIVINO NIÑO,813002933,Territorial,Salud y Protección Social,Corporación Autónoma,5

#Table provider

In [39]:
provider = df[['codigo_proveedor','proveedor_adjudicado','documento_proveedor', 'es_pyme','tipodocproveedor']]

In [42]:
provider.drop_duplicates(inplace=True)

C:\Users\bryan\AppData\Local\Temp\ipykernel_11148\1455118863.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  provider.drop_duplicates(inplace=True)

In [44]:
provider.head()

,codigo_proveedor,proveedor_adjudicado,documento_proveedor,es_pyme,tipodocproveedor
0,716455852,José Darío Bravo Ramírez,10164028,No,Cédula de Ciudadanía
1,704586510,INNOVATECH IT S.A.S - BPO HAPPIFY°,900860807,Si,NIT
2,720225374,LISBETH DAYELLI ROZO SALDAÑA,1073719989,No,Cédula de Ciudadanía
3,716463088,Mike Sepúlveda Valencia,1123633810,No,Cédula de Ciudadanía
4,724422027,MARIA CAMILA VARON CALDERON,1053818566,No,Cédula de Ciudadanía

#Table dim_date

In [169]:
dim_date = pd.concat([df['fecha_de_inicio_del_contrato'], df['fecha_de_fin_del_contrato'], df['fecha_de_firma'], df['fecha_inicio_liquidacion'], df['fecha_fin_liquidacion']])

In [170]:
date = pd.DataFrame(dim_date.drop_duplicates().dropna().reset_index(drop=True), columns=['date'])

In [171]:
date['date'] = pd.to_datetime(date['date'], format='ISO8601', errors='coerce')

In [178]:
df.loc[df['fecha_de_fin_del_contrato'] >= '2100-01-01T00:00:00.000', ['fecha_de_inicio_del_contrato', 'fecha_de_fin_del_contrato','estado_contrato','nombre_entidad','proveedor_adjudicado','valor_del_contrato']]

,fecha_de_inicio_del_contrato,fecha_de_fin_del_contrato,estado_contrato,nombre_entidad,proveedor_adjudicado,valor_del_contrato
240276,2024-03-12T00:00:00.000,2924-12-31T00:00:00.000,Modificado,MINISTERIO DE MINAS Y ENERGIA,Marcia Lorena Parra Velásquez,107800000
326060,2024-04-17T00:00:00.000,2924-08-12T00:00:00.000,En ejecución,MUNICIPIO DE PRADERA,Yessica Maria Amezquita Romero,9800000

In [172]:
date = date.drop_duplicates()

In [204]:
date.dropna(inplace=True)

In [177]:
date.head()

        date
0 2024-01-01
1 2024-01-02
2 2024-01-03
3 2024-01-04
4 2024-01-05

In [ ]:
date['year'] = date['date'].dt.year.astype('Int64')
date['month'] = date['date'].dt.month.astype('Int64')
date['day'] = date['date'].dt.day.astype('Int64')
date['quarter'] = date['date'].dt.quarter.astype('Int64')
date['week'] = date['date'].dt.isocalendar().week.astype('Int64')
date['day_of_week'] = date['date'].dt.dayofweek.astype('Int64')
date['day_name'] = date['date'].dt.day_name()
date['month_name'] = date['date'].dt.month_name()
date['is_weekend'] = date['day_of_week'].isin([5, 6])

In [185]:
date['id_date'] = date['date'].dt.strftime('%Y%m%d').astype('Int64')

In [186]:
date.head()

,date,year,month,day,quarter,week,day_of_week,day_name,month_name,is_weekend,id_date
0,2024-01-01,2024,1,1,1,1,0,Monday,January,False,20240101
1,2024-01-02,2024,1,2,1,1,1,Tuesday,January,False,20240102
2,2024-01-03,2024,1,3,1,1,2,Wednesday,January,False,20240103
3,2024-01-04,2024,1,4,1,1,3,Thursday,January,False,20240104
4,2024-01-05,2024,1,5,1,1,4,Friday,January,False,20240105

#table contract

In [188]:
df.columns

Index(['nombre_entidad', 'nit_entidad', 'departamento', 'ciudad',
       'localizaci_n', 'orden', 'sector', 'rama', 'entidad_centralizada',
       'proceso_de_compra', 'id_contrato', 'referencia_del_contrato',
       'estado_contrato', 'codigo_de_categoria_principal',
       'descripcion_del_proceso', 'tipo_de_contrato',
       'modalidad_de_contratacion', 'justificacion_modalidad_de',
       'fecha_de_firma', 'fecha_de_inicio_del_contrato',
       'fecha_de_fin_del_contrato', 'condiciones_de_entrega',
       'tipodocproveedor', 'documento_proveedor', 'proveedor_adjudicado',
       'es_grupo', 'es_pyme', 'habilita_pago_adelantado', 'liquidaci_n',
       'obligaci_n_ambiental', 'obligaciones_postconsumo', 'reversion',
       'origen_de_los_recursos', 'destino_gasto', 'valor_del_contrato',
       'valor_de_pago_adelantado', 'valor_facturado',
       'valor_pendiente_de_pago', 'valor_pagado', 'valor_amortizado',
       'valor_pendiente_de', 'valor_pendiente_de_ejecucion', 'saldo_cdp',
       'saldo_vigencia', 'espostconflicto', 'dias_adicionados',
       'puntos_del_acuerdo', 'pilares_del_acuerdo', 'urlproceso',
       'nombre_representante_legal', 'nacionalidad_representante_legal',
       'domicilio_representante_legal',
       'tipo_de_identificaci_n_representante_legal',
       'identificaci_n_representante_legal', 'g_nero_representante_legal',
       'presupuesto_general_de_la_nacion_pgn',
       'sistema_general_de_participaciones', 'sistema_general_de_regal_as',
       'recursos_propios_alcald_as_gobernaciones_y_resguardos_ind_genas_',
       'recursos_de_credito', 'recursos_propios', 'ultima_actualizacion',
       'codigo_entidad', 'codigo_proveedor', 'objeto_del_contrato',
       'duraci_n_del_contrato', 'nombre_del_banco', 'tipo_de_cuenta',
       'n_mero_de_cuenta', 'el_contrato_puede_ser_prorrogado',
       'nombre_ordenador_del_gasto', 'tipo_de_documento_ordenador_del_gasto',
       'n_mero_de_documento_ordenador_del_gasto', 'nombre_supervisor',
       'tipo_de_documento_supervisor', 'n_mero_de_documento_supervisor',
       'nombre_ordenador_de_pago', 'tipo_de_documento_ordenador_de_pago',
       'n_mero_de_documento_ordenador_de_pago', 'documentos_tipo',
       'descripcion_documentos_tipo', 'fecha_inicio_liquidacion',
       'fecha_fin_liquidacion', 'fecha_de_notificaci_n_de_prorrogaci_n'],
      dtype='object')

In [190]:
contract = df[['id_contrato','codigo_entidad','codigo_proveedor','fecha_de_inicio_del_contrato',
               'fecha_de_fin_del_contrato','fecha_de_firma','fecha_inicio_liquidacion','fecha_fin_liquidacion',
               'estado_contrato','valor_del_contrato','valor_pendiente_de_pago','valor_pagado','tipo_de_contrato',
               'liquidaci_n','obligaci_n_ambiental','espostconflicto']]

In [209]:
contract.head()

,id_contrato,codigo_entidad,codigo_proveedor,fecha_de_inicio_del_contrato,fecha_de_fin_del_contrato,fecha_de_firma,fecha_inicio_liquidacion,fecha_fin_liquidacion,estado_contrato,valor_del_contrato,valor_pendiente_de_pago,valor_pagado,tipo_de_contrato,liquidaci_n,obligaci_n_ambiental,espostconflicto
0,CO1.PCCNTR.5684136,701728222,716455852,20240101,20241231,20231228,<NA>,<NA>,terminado,196400000,17561600,178838400,Prestación de servicios,No,No,No
1,CO1.PCCNTR.5671442,702350083,704586510,20240101,20241231,20231222,<NA>,<NA>,terminado,575677017,575677017,0,Prestación de servicios,No,No,No
2,CO1.PCCNTR.5707355,705985851,720225374,20240101,20240131,20240101,<NA>,<NA>,terminado,1730400,1730400,0,Prestación de servicios,No,No,No
3,CO1.PCCNTR.5699842,701192130,716463088,20240101,20241231,20231229,20241231,20250531,Cerrado,7902625,7902625,0,Otro,Si,No,No
4,CO1.PCCNTR.5707593,714657632,724422027,20240101,20240331,20240101,20240401,20240630,Modificado,19474560,3951360,15523200,Prestación de servicios,Si,No,No

In [206]:
contract['fecha_de_inicio_del_contrato'] = pd.to_datetime(contract['fecha_de_inicio_del_contrato'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')

C:\Users\bryan\AppData\Local\Temp\ipykernel_11148\3561251841.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  contract['fecha_de_inicio_del_contrato'] = pd.to_datetime(contract['fecha_de_inicio_del_contrato'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')

In [208]:
contract['fecha_de_fin_del_contrato'] = pd.to_datetime(contract['fecha_de_fin_del_contrato'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')

contract['fecha_de_firma'] = pd.to_datetime(contract['fecha_de_firma'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')

contract['fecha_inicio_liquidacion'] = pd.to_datetime(contract['fecha_inicio_liquidacion'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')

contract['fecha_fin_liquidacion'] = pd.to_datetime(contract['fecha_fin_liquidacion'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')

C:\Users\bryan\AppData\Local\Temp\ipykernel_11148\2383786846.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  contract['fecha_de_fin_del_contrato'] = pd.to_datetime(contract['fecha_de_fin_del_contrato'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')
C:\Users\bryan\AppData\Local\Temp\ipykernel_11148\2383786846.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  contract['fecha_de_firma'] = pd.to_datetime(contract['fecha_de_firma'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')
C:\Users\bryan\AppData\Local\Temp\ipykernel_11148\2383786846.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  contract['fecha_inicio_liquidacion'] = pd.to_datetime(contract['fecha_inicio_liquidacion'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')
C:\Users\bryan\AppData\Local\Temp\ipykernel_11148\2383786846.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  contract['fecha_fin_liquidacion'] = pd.to_datetime(contract['fecha_fin_liquidacion'], format='ISO8601', errors='coerce').dt.strftime('%Y%m%d').astype('Int64')

In [230]:
contract.loc[contract['fecha_de_firma'].isnull(), ['fecha_de_firma','fecha_de_inicio_del_contrato', 'fecha_de_fin_del_contrato','estado_contrato','valor_del_contrato']]

,fecha_de_firma,fecha_de_inicio_del_contrato,fecha_de_fin_del_contrato,estado_contrato,valor_del_contrato
10628,<NA>,20240110,20340109,enviado Proveedor,0
273961,<NA>,20240322,20240621,Cancelado,0